/* ===== Certification-exam vocabulary sets =====
   Hardcoded (not pulled from a live Google Sheet like the general-language
   quiz) because these are fixed, official-level word lists rather than a
   user-curated sheet. Word shape matches addWord()'s output in quiz.js so
   selectExamSet() can feed these arrays straight into vocabularyList/
   readingList without any parsing step.
   JLPT N5 source: kanshudo.com/collections/wikipedia_jlpt (Wikipedia JLPT
   vocab list). English glosses are from that source; Traditional Chinese
   glosses were added by hand for the answer-language toggle. */
const EXAM_VOCAB = {
    jlpt_n5: [
        { word: '時間', kana: 'じかん', meaning: '時間', english: 'time' },
        { word: '会社', kana: 'かいしゃ', meaning: '公司', english: 'company; corporation' },
        { word: '電話', kana: 'でんわ', meaning: '電話', english: 'telephone call; phone' },
        { word: '今日', kana: 'きょう', meaning: '今天', english: 'today' },
        { word: '写真', kana: 'しゃしん', meaning: '照片', english: 'photograph; photo; picture' },
        { word: '全部', kana: 'ぜんぶ', meaning: '全部', english: 'all; entire; whole' },
        { word: '大学', kana: 'だいがく', meaning: '大學', english: 'university; college' },
        { word: '大きな', kana: 'おおきな', meaning: '大的', english: 'big; large; great' },
        { word: '文章', kana: 'ぶんしょう', meaning: '文章；句子', english: 'sentence; article; composition' },
        { word: '問題', kana: 'もんだい', meaning: '問題', english: 'question; problem' },
        { word: 'ください', kana: 'ください', meaning: '請給我；請', english: 'please give me; please do for me' },
        { word: '見る', kana: 'みる', meaning: '看；看見', english: 'to see; to look; to watch' },
        { word: 'できる', kana: 'できる', meaning: '能夠；可以', english: 'to be able to do; to be possible' },
        { word: '旅行', kana: 'りょこう', meaning: '旅行', english: 'travel; trip' },
        { word: '家庭', kana: 'かてい', meaning: '家庭', english: 'home; family; household' },
        { word: 'また', kana: 'また', meaning: '又；再', english: 'again; and; also' },
        { word: '学校', kana: 'がっこう', meaning: '學校', english: 'school' },
        { word: '質問', kana: 'しつもん', meaning: '提問；詢問', english: 'question; inquiry' },
        { word: '番号', kana: 'ばんごう', meaning: '號碼', english: 'number; series of digits' },
        { word: '今年', kana: 'ことし', meaning: '今年', english: 'this year' },
        { word: '結婚', kana: 'けっこん', meaning: '結婚', english: 'marriage' },
        { word: '自分', kana: 'じぶん', meaning: '自己', english: 'myself; yourself; oneself' },
        { word: '高い', kana: 'たかい', meaning: '高的；貴的', english: 'high; tall; expensive' },
        { word: '新聞', kana: 'しんぶん', meaning: '報紙', english: 'newspaper' },
        { word: '仕事', kana: 'しごと', meaning: '工作', english: 'work; job; business; occupation' },
        { word: '学生', kana: 'がくせい', meaning: '學生', english: 'student' },
        { word: '一つ', kana: 'ひとつ', meaning: '一個', english: 'one' },
        { word: '名前', kana: 'なまえ', meaning: '名字', english: 'name; full name' },
        { word: '先生', kana: 'せんせい', meaning: '老師', english: 'teacher; master; doctor' },
        { word: '一人', kana: 'ひとり', meaning: '一個人；獨自', english: 'one person; alone' },
        { word: '便利', kana: 'べんり', meaning: '方便', english: 'convenient; handy; useful' },
        { word: '映画', kana: 'えいが', meaning: '電影', english: 'movie; film' },
        { word: 'する', kana: 'する', meaning: '做', english: 'to do; to cause to become' },
        { word: 'ページ', kana: 'ページ', meaning: '頁', english: 'page' },
        { word: 'など', kana: 'など', meaning: '等等', english: 'et cetera; etc.; and the like' },
        { word: 'でも', kana: 'でも', meaning: '但是', english: 'but; however; though' },
        { word: 'なる', kana: 'なる', meaning: '變成', english: 'to become; to get; to grow' },
        { word: 'では', kana: 'では', meaning: '那麼', english: 'then; well; so' },
        { word: 'その', kana: 'その', meaning: '那個', english: 'that; the' },
        { word: 'より', kana: 'より', meaning: '比；從', english: 'than; from; out of' },
        { word: 'スポーツ', kana: 'スポーツ', meaning: '運動', english: 'sport; sports' },
        { word: 'よく', kana: 'よく', meaning: '經常；很好地', english: 'nicely; properly; well; frequently' },
        { word: 'これ', kana: 'これ', meaning: '這個', english: 'this' },
        { word: 'いい', kana: 'いい', meaning: '好', english: 'good; excellent; fine; nice' },
        { word: '後ろ', kana: 'うしろ', meaning: '後面', english: 'back; behind; rear' },
        { word: '料理', kana: 'りょうり', meaning: '料理；烹飪', english: 'cooking; cookery; cuisine' },
        { word: '家族', kana: 'かぞく', meaning: '家人', english: 'family; members of a family' },
        { word: 'みんな', kana: 'みんな', meaning: '大家', english: 'all; everyone; everybody' },
        { word: 'ある', kana: 'ある', meaning: '有（無生物）', english: 'to be; to exist; to have' },
        { word: 'かわいい', kana: 'かわいい', meaning: '可愛', english: 'cute; adorable; charming' },
        { word: '毎日', kana: 'まいにち', meaning: '每天', english: 'every day' },
        { word: '意味', kana: 'いみ', meaning: '意思', english: 'meaning; significance' },
        { word: '音楽', kana: 'おんがく', meaning: '音樂', english: 'music; musical movement' },
        { word: '買い物', kana: 'かいもの', meaning: '購物', english: 'shopping; purchased goods' },
        { word: '時計', kana: 'とけい', meaning: '時鐘；手錶', english: 'watch; clock; timepiece' },
        { word: '国', kana: 'くに', meaning: '國家', english: 'country; state; region' },
        { word: '手', kana: 'て', meaning: '手', english: 'hand; arm; forepaw' },
        { word: '十', kana: 'じゅう', meaning: '十', english: 'ten' },
        { word: '後', kana: 'あと', meaning: '之後', english: 'behind; rear; after; later' },
        { word: '私', kana: 'わたし', meaning: '我', english: 'I; me' },
        { word: '新しい', kana: 'あたらしい', meaning: '新的', english: 'new; novel; fresh; recent' },
        { word: '道', kana: 'みち', meaning: '道路', english: 'road; street; way; path' },
        { word: '四', kana: 'よん', meaning: '四', english: 'four' },
        { word: '木', kana: 'き', meaning: '樹木', english: 'tree; shrub; bush; wood; timber' },
        { word: '六', kana: 'ろく', meaning: '六', english: 'six' },
        { word: '年', kana: 'とし', meaning: '年；年齡', english: 'year; age' },
        { word: '八', kana: 'はち', meaning: '八', english: 'eight' },
        { word: '何', kana: 'なに', meaning: '什麼', english: 'what; how many' },
        { word: '七', kana: 'しち', meaning: '七', english: 'seven' },
        { word: '百', kana: 'ひゃく', meaning: '一百', english: '100; hundred' },
        { word: '千', kana: 'せん', meaning: '一千', english: '1,000; thousand' },
        { word: '海', kana: 'うみ', meaning: '海', english: 'sea; ocean; waters' },
        { word: '花', kana: 'はな', meaning: '花', english: 'flower; blossom; bloom; petal' },
        { word: '色', kana: 'いろ', meaning: '顏色', english: 'colour; color; complexion' },
        { word: '少し', kana: 'すこし', meaning: '一點；少許', english: 'small quantity; little; few' },
        { word: '銀行', kana: 'ぎんこう', meaning: '銀行', english: 'bank' },
        { word: '自動車', kana: 'じどうしゃ', meaning: '汽車', english: 'automobile' },
        { word: '部屋', kana: 'へや', meaning: '房間', english: 'room; chamber; apartment' },
        { word: '子供', kana: 'こども', meaning: '小孩', english: 'child; children' },
        { word: '良い', kana: 'よい', meaning: '好', english: 'good; excellent; fine; nice' },
        { word: '黒', kana: 'くろ', meaning: '黑色', english: 'black' },
        { word: '九', kana: 'きゅう', meaning: '九', english: 'nine' },
        { word: '北', kana: 'きた', meaning: '北', english: 'north' },
        { word: '西', kana: 'にし', meaning: '西', english: 'west' },
        { word: '二人', kana: 'ふたり', meaning: '兩個人', english: 'two persons; two people; pair' },
        { word: '南', kana: 'みなみ', meaning: '南', english: 'south' },
        { word: '下', kana: 'した', meaning: '下面', english: 'below; down; under; bottom' },
        { word: '今', kana: 'いま', meaning: '現在', english: 'now; the present time' },
        { word: '電気', kana: 'でんき', meaning: '電；電燈', english: 'electricity; (electric) light' },
        { word: '一緒', kana: 'いっしょ', meaning: '一起', english: 'together; at the same time' },
        { word: 'ニュース', kana: 'ニュース', meaning: '新聞（消息）', english: 'news' },
        { word: 'もっと', kana: 'もっと', meaning: '更', english: '(some) more; even more' },
        { word: '足', kana: 'あし', meaning: '腳', english: 'foot; leg' },
        { word: '声', kana: 'こえ', meaning: '聲音', english: 'voice' },
        { word: '庭', kana: 'にわ', meaning: '庭院', english: 'garden; yard; courtyard' },
        { word: '友達', kana: 'ともだち', meaning: '朋友', english: 'friend; companion' },
        { word: '青', kana: 'あお', meaning: '藍色', english: 'blue; green' },
        { word: '言葉', kana: 'ことば', meaning: '語言；詞語', english: 'language; dialect; word' },
        { word: '地図', kana: 'ちず', meaning: '地圖', english: 'map' },

        { word: '自転車', kana: 'じてんしゃ', meaning: '腳踏車', english: 'bicycle' },
        { word: '女の子', kana: 'おんなのこ', meaning: '女孩', english: 'girl; daughter' },
        { word: '町', kana: 'まち', meaning: '城鎮', english: 'town; block; neighbourhood' },
        { word: '夜', kana: 'よる', meaning: '晚上', english: 'evening; night' },
        { word: '言う', kana: 'いう', meaning: '說', english: 'to say; to utter; to declare' },
        { word: 'ここ', kana: 'ここ', meaning: '這裡', english: 'here; this place' },
        { word: '大きい', kana: 'おおきい', meaning: '大的', english: 'big; large; great; loud' },
        { word: '春', kana: 'はる', meaning: '春天', english: 'spring; springtime' },
        { word: '英語', kana: 'えいご', meaning: '英文', english: 'English (language)' },
        { word: '話', kana: 'はなし', meaning: '話；故事', english: 'talk; speech; chat; story' },
        { word: 'それ', kana: 'それ', meaning: '那個', english: 'that (indicating item near listener)' },
        { word: '箱', kana: 'はこ', meaning: '箱子', english: 'box; case; chest; package' },
        { word: '病院', kana: 'びょういん', meaning: '醫院', english: 'hospital' },
        { word: '半', kana: 'はん', meaning: '一半', english: 'half; semi-' },
        { word: '雑誌', kana: 'ざっし', meaning: '雜誌', english: 'journal; magazine; periodical' },
        { word: '明日', kana: 'あした', meaning: '明天', english: 'tomorrow' },
        { word: '机', kana: 'つくえ', meaning: '書桌', english: 'desk' },
        { word: '動物', kana: 'どうぶつ', meaning: '動物', english: 'animal' },
        { word: '外国', kana: 'がいこく', meaning: '外國', english: 'foreign country' },
        { word: '同じ', kana: 'おなじ', meaning: '相同', english: 'same; identical; equal' },
        { word: '使う', kana: 'つかう', meaning: '使用', english: 'to use' },
        { word: '財布', kana: 'さいふ', meaning: '錢包', english: 'purse; handbag; wallet' },
        { word: '大切', kana: 'たいせつ', meaning: '重要', english: 'important; necessary' },
        { word: '作る', kana: 'つくる', meaning: '製作', english: 'to make; to produce' },
        { word: '服', kana: 'ふく', meaning: '衣服', english: 'clothes' },
        { word: '教室', kana: 'きょうしつ', meaning: '教室', english: 'classroom' },
        { word: '公園', kana: 'こうえん', meaning: '公園', english: '(public) park' },
        { word: '右', kana: 'みぎ', meaning: '右邊', english: 'right; right hand side' },
        { word: '有名', kana: 'ゆうめい', meaning: '有名', english: 'famous' },
        { word: '歌', kana: 'うた', meaning: '歌曲', english: 'song; classical Japanese poetry' },
        { word: '村', kana: 'むら', meaning: '村莊', english: 'village' },
        { word: '好き', kana: 'すき', meaning: '喜歡', english: 'liking; fondness; love' },
        { word: '医者', kana: 'いしゃ', meaning: '醫生', english: '(medical) doctor; physician' },
        { word: '靴', kana: 'くつ', meaning: '鞋子', english: 'shoes; boots; footwear' },
        { word: '大好き', kana: 'だいすき', meaning: '非常喜歡', english: 'loveable; very likeable' },
        { word: '昨日', kana: 'きのう', meaning: '昨天', english: 'yesterday' },
        { word: '一番', kana: 'いちばん', meaning: '第一；最', english: 'number one; first; best' },
        { word: 'どう', kana: 'どう', meaning: '如何', english: 'how; in what way' },
        { word: '玄関', kana: 'げんかん', meaning: '玄關；門口', english: 'entranceway; entry hall' },
        { word: '兄弟', kana: 'きょうだい', meaning: '兄弟姊妹', english: 'siblings; brothers and sisters' },
        { word: '読む', kana: 'よむ', meaning: '讀；閱讀', english: 'to read; to count' },
        { word: 'あなた', kana: 'あなた', meaning: '你', english: 'you (referring to equal or lower status)' },
        { word: '秋', kana: 'あき', meaning: '秋天', english: 'autumn; fall' },
        { word: '犬', kana: 'いぬ', meaning: '狗', english: 'dog' },
        { word: '練習', kana: 'れんしゅう', meaning: '練習', english: 'practice; practising' },
        { word: '勉強', kana: 'べんきょう', meaning: '學習；用功', english: 'study; diligence' },
        { word: '雨', kana: 'あめ', meaning: '雨', english: 'rain' },
        { word: 'ちょっと', kana: 'ちょっと', meaning: '一下；稍微', english: 'just a minute; short time' },
        { word: '雪', kana: 'ゆき', meaning: '雪', english: 'snow' },
        { word: 'お金', kana: 'おかね', meaning: '錢', english: 'money' },
        { word: '縦', kana: 'たて', meaning: '縱向；高度', english: 'the vertical; height' },
        { word: '出口', kana: 'でぐち', meaning: '出口', english: 'exit; gateway; way out' },
        { word: '川', kana: 'かわ', meaning: '河川', english: 'river; stream' },
        { word: 'いつ', kana: 'いつ', meaning: '何時', english: 'when; how soon' },
        { word: '午後', kana: 'ごご', meaning: '下午', english: 'afternoon; p.m.' },
        { word: '角', kana: 'かど', meaning: '角落', english: 'corner; edge' },
        { word: '持つ', kana: 'もつ', meaning: '拿；持有', english: 'to hold; to possess' },
        { word: '肉', kana: 'にく', meaning: '肉', english: 'flesh; meat' },
        { word: '鍵', kana: 'かぎ', meaning: '鑰匙；鎖', english: 'key; lock' },
        { word: '始め', kana: 'はじめ', meaning: '開始', english: 'beginning; start; outset' },
        { word: 'あまり', kana: 'あまり', meaning: '不太（接否定）', english: 'remainder; rest; not very (with negative)' },
        { word: '駅', kana: 'えき', meaning: '車站', english: 'station' },
        { word: '大人', kana: 'おとな', meaning: '大人', english: 'adult' },
        { word: 'どの', kana: 'どの', meaning: '哪個', english: 'which; what (way)' },
        { word: '横', kana: 'よこ', meaning: '旁邊；橫向', english: 'horizontal; side-to-side' },
        { word: '天気', kana: 'てんき', meaning: '天氣', english: 'weather; the elements' },
        { word: 'カメラ', kana: 'カメラ', meaning: '相機', english: 'camera' },
        { word: 'ほか', kana: 'ほか', meaning: '其他', english: 'other (place, thing, person)' },
        { word: '知る', kana: 'しる', meaning: '知道', english: 'to know; to be aware' },
        { word: 'テレビ', kana: 'テレビ', meaning: '電視', english: 'television; TV' },
        { word: 'そして', kana: 'そして', meaning: '然後', english: 'and; and then; thus' },
        { word: '去年', kana: 'きょねん', meaning: '去年', english: 'last year' },
        { word: '電車', kana: 'でんしゃ', meaning: '電車', english: 'train; electric train' },
        { word: '今月', kana: 'こんげつ', meaning: '這個月', english: 'this month' },
        { word: '午前', kana: 'ごぜん', meaning: '上午', english: 'morning; a.m.' },
        { word: '少ない', kana: 'すくない', meaning: '少的', english: 'few; a little; scarce' },
        { word: '朝', kana: 'あさ', meaning: '早上', english: 'morning' },
        { word: '大変', kana: 'たいへん', meaning: '非常；辛苦', english: 'very; greatly; immense' },
        { word: '元気', kana: 'げんき', meaning: '有精神；健康', english: 'lively; full of spirit; healthy' },
        { word: '河', kana: 'かわ', meaning: '河川', english: 'river; stream' },
        { word: '野菜', kana: 'やさい', meaning: '蔬菜', english: 'vegetable' },
        { word: '出す', kana: 'だす', meaning: '拿出', english: 'to take out; to put out' },
        { word: 'テーブル', kana: 'テーブル', meaning: '桌子', english: 'table' },
        { word: 'あれ', kana: 'あれ', meaning: '那個（較遠）', english: 'that (distant object or person)' },
        { word: '病気', kana: 'びょうき', meaning: '生病', english: 'illness; disease; sickness' },
        { word: '男の子', kana: 'おとこのこ', meaning: '男孩', english: 'boy; male child' },
        { word: '一', kana: 'いち', meaning: '一', english: 'one; best' },
        { word: '結構', kana: 'けっこう', meaning: '很好；不用了', english: 'splendid; nice; wonderful' },
        { word: '交番', kana: 'こうばん', meaning: '派出所', english: 'police box; small neighborhood police station' },
        { word: '一日', kana: 'ついたち', meaning: '一號（每月）', english: 'first day of the month' },
        { word: '一日', kana: 'いちにち', meaning: '一天', english: 'one day' },
        { word: 'ペット', kana: 'ペット', meaning: '寵物', english: 'pet' },
        { word: 'もう', kana: 'もう', meaning: '已經', english: 'now; soon; already; yet' },
        { word: 'そば', kana: 'そば', meaning: '旁邊', english: 'near; close; beside' },
        { word: '建物', kana: 'たてもの', meaning: '建築物', english: 'building' },
        { word: '大丈夫', kana: 'だいじょうぶ', meaning: '沒問題；不要緊', english: 'safe; all right; OK' },
        { word: '休み', kana: 'やすみ', meaning: '休息；假日', english: 'rest; recess; vacation; holiday' },
        { word: '出る', kana: 'でる', meaning: '出去；出來', english: 'to leave; to exit; to come out' },
        { word: 'シャツ', kana: 'シャツ', meaning: '襯衫', english: 'shirt (underwear or outerwear)' },
        { word: 'いかが', kana: 'いかが', meaning: '如何', english: 'how; in what way; how about' },

        { word: '紙', kana: 'かみ', meaning: '紙', english: 'paper' },
        { word: '来年', kana: 'らいねん', meaning: '明年', english: 'next year' },
        { word: '帽子', kana: 'ぼうし', meaning: '帽子', english: 'hat; cap' },
        { word: '強い', kana: 'つよい', meaning: '強壯的', english: 'strong; powerful' },
        { word: '上手', kana: 'じょうず', meaning: '擅長', english: 'skill; skillful' },
        { word: '外国人', kana: 'がいこくじん', meaning: '外國人', english: 'foreigner' },
        { word: '冬', kana: 'ふゆ', meaning: '冬天', english: 'winter' },
        { word: '掃除', kana: 'そうじ', meaning: '打掃', english: 'cleaning; sweeping' },
        { word: '買う', kana: 'かう', meaning: '買', english: 'to buy; to purchase' },
        { word: '皆さん', kana: 'みなさん', meaning: '大家', english: 'all; everyone' },
        { word: '痛い', kana: 'いたい', meaning: '痛的', english: 'painful; sore' },
        { word: '難しい', kana: 'むずかしい', meaning: '困難的', english: 'difficult; hard' },
        { word: '行く', kana: 'いく', meaning: '去', english: 'to go; to move' },
        { word: '欲しい', kana: 'ほしい', meaning: '想要', english: 'wanted; desired' },
        { word: '鞄', kana: 'かばん', meaning: '包包', english: 'bag; satchel' },
        { word: '二つ', kana: 'ふたつ', meaning: '兩個', english: 'two' },
        { word: '本当', kana: 'ほんとう', meaning: '真的', english: 'truth; reality' },
        { word: '楽しい', kana: 'たのしい', meaning: '開心的', english: 'enjoyable; fun' },
        { word: '今週', kana: 'こんしゅう', meaning: '這週', english: 'this week' },
        { word: 'コート', kana: 'コート', meaning: '外套', english: 'coat; court' },
        { word: '食べ物', kana: 'たべもの', meaning: '食物', english: 'food' },
        { word: '多い', kana: 'おおい', meaning: '多的', english: 'many; numerous' },
        { word: '図書館', kana: 'としょかん', meaning: '圖書館', english: 'library' },
        { word: '黄色', kana: 'きいろ', meaning: '黃色', english: 'yellow; amber' },
        { word: '洗濯', kana: 'せんたく', meaning: '洗衣服', english: 'washing; laundry' },
        { word: '初め', kana: 'はじめ', meaning: '開始', english: 'beginning; start' },
        { word: '妹', kana: 'いもうと', meaning: '妹妹', english: 'younger sister' },
        { word: '窓', kana: 'まど', meaning: '窗戶', english: 'window' },
        { word: '授業', kana: 'じゅぎょう', meaning: '上課', english: 'lesson; class work' },
        { word: '誰', kana: 'だれ', meaning: '誰', english: 'who' },
        { word: '耳', kana: 'みみ', meaning: '耳朵', english: 'ear; hearing' },
        { word: '広い', kana: 'ひろい', meaning: '寬廣的', english: 'spacious; vast; wide' },
        { word: '飛行機', kana: 'ひこうき', meaning: '飛機', english: 'aeroplane; aircraft' },
        { word: '毎年', kana: 'まいとし', meaning: '每年', english: 'every year; yearly' },
        { word: '洋服', kana: 'ようふく', meaning: '西式服裝', english: 'Western-style clothes' },
        { word: '階段', kana: 'かいだん', meaning: '樓梯', english: 'stairs; staircase' },
        { word: 'ボタン', kana: 'ボタン', meaning: '按鈕', english: 'button' },
        { word: '緑', kana: 'みどり', meaning: '綠色', english: 'green; greenery' },
        { word: 'いいえ', kana: 'いいえ', meaning: '不是', english: 'no; nay' },
        { word: '取る', kana: 'とる', meaning: '拿；取', english: 'to take; to pick up' },
        { word: '呼ぶ', kana: 'よぶ', meaning: '呼喚', english: 'to call out; to invoke' },
        { word: '生徒', kana: 'せいと', meaning: '學生', english: 'pupil' },
        { word: 'お茶', kana: 'おちゃ', meaning: '茶', english: 'tea' },
        { word: '二日', kana: 'ふつか', meaning: '二號；兩天', english: 'second day of month; two days' },
        { word: '両親', kana: 'りょうしん', meaning: '雙親', english: 'parents' },
        { word: '三つ', kana: 'みつつ', meaning: '三個', english: 'three' },
        { word: 'こちら', kana: 'こちら', meaning: '這邊', english: 'this way; this direction' },
        { word: '毎週', kana: 'まいしゅう', meaning: '每週', english: 'every week' },
        { word: '魚', kana: 'さかな', meaning: '魚', english: 'fish' },
        { word: '丈夫', kana: 'じょうぶ', meaning: '健壯；堅固', english: 'healthy; robust; strong' },
        { word: 'お母さん', kana: 'おかあさん', meaning: '媽媽', english: 'mother' },
        { word: 'この', kana: 'この', meaning: '這個', english: 'this' },
        { word: '時々', kana: 'ときどき', meaning: '有時', english: 'sometimes; at times' },
        { word: '長い', kana: 'ながい', meaning: '長的', english: 'long (distance/time)' },
        { word: '初めて', kana: 'はじめて', meaning: '第一次', english: 'for the first time' },
        { word: '手紙', kana: 'てがみ', meaning: '信', english: 'letter' },
        { word: '門', kana: 'もん', meaning: '大門', english: 'gate; branch' },
        { word: '夏休み', kana: 'なつやすみ', meaning: '暑假', english: 'summer vacation' },
        { word: '絵', kana: 'え', meaning: '畫', english: 'picture; drawing; painting' },
        { word: '先月', kana: 'せんげつ', meaning: '上個月', english: 'last month' },
        { word: 'こんな', kana: 'こんな', meaning: '這樣的', english: 'such; like this' },
        { word: '十日', kana: 'とおか', meaning: '十號；十天', english: 'tenth day; ten days' },
        { word: '毎月', kana: 'まいつき', meaning: '每個月', english: 'every month' },
        { word: '七日', kana: 'なのか', meaning: '七號；七天', english: 'seventh day; seven days' },
        { word: '近い', kana: 'ちかい', meaning: '近的', english: 'near; close; short' },
        { word: '台所', kana: 'だいどころ', meaning: '廚房', english: 'kitchen; financial situation' },
        { word: '作文', kana: 'さくぶん', meaning: '作文', english: 'writing; composition' },
        { word: '九日', kana: 'ここのか', meaning: '九號；九天', english: 'ninth day; nine days' },
        { word: '来月', kana: 'らいげつ', meaning: '下個月', english: 'next month' },
        { word: '静か', kana: 'しずか', meaning: '安靜', english: 'quiet; silent; slow' },
        { word: '果物', kana: 'くだもの', meaning: '水果', english: 'fruit' },
        { word: 'なぜ', kana: 'なぜ', meaning: '為什麼', english: 'why; how' },
        { word: '八日', kana: 'ようか', meaning: '八號；八天', english: 'eighth day; eight days' },
        { word: '眼鏡', kana: 'めがね', meaning: '眼鏡', english: 'spectacles; glasses' },
        { word: '地下鉄', kana: 'ちかてつ', meaning: '地下鐵', english: 'underground train; subway' },
        { word: '夕方', kana: 'ゆうがた', meaning: '傍晚', english: 'evening; dusk' },
        { word: '早い', kana: 'はやい', meaning: '快的；早的', english: 'fast; quick; early' },
        { word: 'ゼロ', kana: 'ゼロ', meaning: '零', english: 'zero; nought' },
        { word: 'まだ', kana: 'まだ', meaning: '還沒；仍然', english: 'as yet; still; not yet' },
        { word: '戸', kana: 'と', meaning: '門；門扇', english: 'door; shutter' },
        { word: '終わる', kana: 'おわる', meaning: '結束', english: 'to finish; to end; to close' },
        { word: '売る', kana: 'うる', meaning: '賣', english: 'to sell' },
        { word: 'じゃ', kana: 'じゃ', meaning: '那麼', english: 'then; well; so' },
        { word: 'たくさん', kana: 'たくさん', meaning: '很多', english: 'a lot; lots; plenty; many' },
        { word: '冷蔵庫', kana: 'れいぞうこ', meaning: '冰箱', english: 'refrigerator' },
        { word: '椅子', kana: 'いす', meaning: '椅子', english: 'chair; stool; post' },
        { word: '大勢', kana: 'おおぜい', meaning: '很多人', english: 'many; crowd; great number' },
        { word: '嫌い', kana: 'きらい', meaning: '討厭', english: 'dislike; hate; suspicion' },
        { word: '留学生', kana: 'りゅうがくせい', meaning: '留學生', english: 'overseas student' },
        { word: 'お父さん', kana: 'おとうさん', meaning: '爸爸', english: 'father; dad; papa' },
        { word: '牛肉', kana: 'ぎゅうにく', meaning: '牛肉', english: 'beef' },
        { word: 'バス', kana: 'バス', meaning: '公車', english: 'bus; bath' },
        { word: '鳥', kana: 'とり', meaning: '鳥', english: 'bird; bird meat' },
        { word: '先週', kana: 'せんしゅう', meaning: '上週', english: 'last week' },
        { word: '橋', kana: 'はし', meaning: '橋', english: 'bridge' },
        { word: '四つ', kana: 'よつつ', meaning: '四個', english: 'four' },
        { word: '古い', kana: 'ふるい', meaning: '舊的', english: 'old; aged; ancient' },
        { word: '明るい', kana: 'あかるい', meaning: '明亮的', english: 'bright; colourful; cheerful' },
        { word: '入る', kana: 'はいる', meaning: '進入', english: 'to enter; to go into' },
        { word: 'ベッド', kana: 'ベッド', meaning: '床', english: 'bed' },

        { word: '茶色', kana: 'ちゃいろ', meaning: '棕色', english: 'light brown; tawny' },
        { word: '池', kana: 'いけ', meaning: '池塘', english: 'pond' },
        { word: '来週', kana: 'らいしゅう', meaning: '下週', english: 'next week' },
        { word: '大使館', kana: 'たいしかん', meaning: '大使館', english: 'embassy' },
        { word: '警官', kana: 'けいかん', meaning: '警察', english: 'police officer' },
        { word: '昼', kana: 'ひる', meaning: '中午；白天', english: 'noon; daytime' },
        { word: '散歩', kana: 'さんぽ', meaning: '散步', english: 'walk; stroll' },
        { word: '人', kana: 'にん', meaning: '（人數量詞）；人', english: 'counter for people; person' },
        { word: '本', kana: 'ほん', meaning: '書', english: 'book; volume; script' },
        { word: '中', kana: 'なか', meaning: '裡面；中間', english: 'inside; among' },
        { word: '上', kana: 'うえ', meaning: '上面', english: 'above; top; summit' },
        { word: '漢字', kana: 'かんじ', meaning: '漢字', english: 'Chinese characters; kanji' },
        { word: '二', kana: 'に', meaning: '二', english: 'two' },
        { word: '弟', kana: 'おとうと', meaning: '弟弟', english: 'younger brother' },
        { word: '家', kana: 'や', meaning: '店（接尾詞）', english: 'shop; seller (suffix)' },
        { word: '女', kana: 'おんな', meaning: '女性', english: 'female; woman' },
        { word: '三', kana: 'さん', meaning: '三', english: 'three' },
        { word: 'ポケット', kana: 'ポケット', meaning: '口袋', english: 'pocket' },
        { word: '前', kana: 'まえ', meaning: '前面；之前', english: 'in front; before' },
        { word: '方', kana: 'かた', meaning: '方向；人（敬語）', english: 'direction; person (honorific)' },
        { word: '目', kana: 'め', meaning: '眼睛', english: 'eye; eyesight' },
        { word: '物', kana: 'もの', meaning: '東西', english: 'thing; object; possessions' },
        { word: '辞書', kana: 'じしょ', meaning: '字典', english: 'dictionary; lexicon' },
        { word: '荷物', kana: 'にもつ', meaning: '行李', english: 'luggage; burden' },
        { word: '五', kana: 'ご', meaning: '五', english: 'five' },
        { word: '男', kana: 'おとこ', meaning: '男性', english: 'man; male' },
        { word: '小さい', kana: 'ちいさい', meaning: '小的', english: 'small; little; tiny' },
        { word: '所', kana: 'ところ', meaning: '地方', english: 'place; spot; address' },
        { word: '先', kana: 'さき', meaning: '前方；先前', english: 'previous; point; tip' },
        { word: '晴れ', kana: 'はれ', meaning: '晴天', english: 'clear weather; formal' },
        { word: '一昨年', kana: 'おととし', meaning: '前年', english: 'year before last' },
        { word: '次', kana: 'じ', meaning: '下一個', english: 'next; hypo-' },
        { word: '水', kana: 'すい', meaning: '星期三；水', english: 'Wednesday; shaved ice' },
        { word: '薬', kana: 'くすり', meaning: '藥', english: 'medicine; drugs' },
        { word: '書く', kana: 'かく', meaning: '寫', english: 'to write; to draw' },
        { word: '頭', kana: 'あたま', meaning: '頭', english: 'head; hair' },
        { word: '万', kana: 'まん', meaning: '萬', english: '10,000; myriad' },
        { word: '白', kana: 'はく', meaning: '白色', english: 'white; mullet fry' },
        { word: '低い', kana: 'ひくい', meaning: '低的', english: 'low (rank, position)' },
        { word: '箸', kana: 'はし', meaning: '筷子', english: 'chopsticks' },
        { word: '多分', kana: 'たぶん', meaning: '大概', english: 'perhaps; probably' },
        { word: '車', kana: 'くるま', meaning: '車子', english: 'car; automobile; wheel' },
        { word: '走る', kana: 'はしる', meaning: '跑；行駛', english: 'to run; to drive' },
        { word: '白い', kana: 'しろい', meaning: '白色的', english: 'white' },
        { word: '店', kana: 'みせ', meaning: '店', english: 'store; shop; restaurant' },
        { word: '押す', kana: 'おす', meaning: '推；按', english: 'to push; to press' },
        { word: '郵便局', kana: 'ゆうびんきょく', meaning: '郵局', english: 'post office' },
        { word: '嫌', kana: 'いや', meaning: '討厭', english: 'disagreeable; unpleasant' },
        { word: '五つ', kana: 'いつつ', meaning: '五個', english: 'five' },
        { word: '下手', kana: 'へた', meaning: '笨拙；不擅長', english: 'unskillful; awkward' },
        { word: '浴びる', kana: 'あびる', meaning: '沖（澡）；淋', english: 'to bathe; to suffer' },
        { word: '食べる', kana: 'たべる', meaning: '吃', english: 'to eat; to subsist on' },
        { word: 'いつも', kana: 'いつも', meaning: '總是', english: 'always; usually' },
        { word: '立派', kana: 'りっぱ', meaning: '出色；壯觀', english: 'splendid; praiseworthy' },
        { word: 'コーヒー', kana: 'コーヒー', meaning: '咖啡', english: 'coffee' },
        { word: 'とても', kana: 'とても', meaning: '非常', english: 'very; awfully' },
        { word: '切る', kana: 'きる', meaning: '切', english: 'to cut; to sever' },
        { word: '姉', kana: 'あね', meaning: '姊姊', english: 'older sister' },
        { word: 'ホテル', kana: 'ホテル', meaning: '飯店', english: 'hotel' },
        { word: '頼む', kana: 'たのむ', meaning: '拜託；委託', english: 'to request; to reserve' },
        { word: '切手', kana: 'きって', meaning: '郵票', english: 'stamp; certificate' },
        { word: '夏', kana: 'なつ', meaning: '夏天', english: 'summer' },
        { word: '赤い', kana: 'あかい', meaning: '紅色的', english: 'red' },
        { word: '着る', kana: 'きる', meaning: '穿（衣服）', english: 'to wear; to bear' },
        { word: '祖父', kana: 'そふ', meaning: '祖父', english: 'grandfather; old man' },
        { word: '隣', kana: 'となり', meaning: '隔壁', english: 'neighbor; next door' },
        { word: '山', kana: 'やま', meaning: '山', english: 'mountain; hill; mine' },
        { word: '熱い', kana: 'あつい', meaning: '熱的', english: 'hot; passionate' },
        { word: '面白い', kana: 'おもしろい', meaning: '有趣的', english: 'interesting; amusing' },
        { word: '映画館', kana: 'えいがかん', meaning: '電影院', english: 'movie theatre; cinema' },
        { word: '牛乳', kana: 'ぎゅうにゅう', meaning: '牛奶', english: 'milk' },
        { word: 'いくつ', kana: 'いくつ', meaning: '幾個；幾歲', english: 'how many; how old' },
        { word: '風邪', kana: 'かぜ', meaning: '感冒', english: 'common cold; flu' },
        { word: '掛ける', kana: 'かける', meaning: '掛；坐', english: 'to hang; to sit' },
        { word: '鼻', kana: 'はな', meaning: '鼻子', english: 'nose' },
        { word: '交差点', kana: 'こうさてん', meaning: '十字路口', english: 'crossing; intersection' },
        { word: '砂糖', kana: 'さとう', meaning: '砂糖', english: 'sugar' },
        { word: '上着', kana: 'うわぎ', meaning: '外套', english: 'coat; jacket; outer garment' },
        { word: '黒い', kana: 'くろい', meaning: '黑色的', english: 'black; dark' },
        { word: '歯', kana: 'は', meaning: '牙齒', english: 'tooth' },
        { word: '卵', kana: 'たまご', meaning: '蛋', english: 'eggs; hen egg' },
        { word: '向こう', kana: 'むこう', meaning: '對面；那邊', english: 'opposite side; over there' },
        { word: '塩', kana: 'しお', meaning: '鹽', english: 'salt' },
        { word: 'パン', kana: 'パン', meaning: '麵包', english: 'bread; pastries; pan' },
        { word: '寝る', kana: 'ねる', meaning: '睡覺', english: 'to lie down; to go to bed' },
        { word: '廊下', kana: 'ろうか', meaning: '走廊', english: 'corridor; hallway' },
        { word: '安い', kana: 'やすい', meaning: '便宜的', english: 'cheap; calm' },
        { word: '渡す', kana: 'わたす', meaning: '遞交', english: 'to ferry; to lay across' },
        { word: '紅茶', kana: 'こうちゃ', meaning: '紅茶', english: 'black tea' },
        { word: 'パーティー', kana: 'パーティー', meaning: '派對', english: 'party' },
        { word: '降りる', kana: 'おりる', meaning: '下（車）', english: 'to descend; to get off' },
        { word: '風呂', kana: 'ふろ', meaning: '浴缸；洗澡', english: 'bath; bathtub; bathroom' },
        { word: '喫茶店', kana: 'きっさてん', meaning: '咖啡廳', english: 'coffee shop; cafe' },
        { word: '毎朝', kana: 'まいあさ', meaning: '每天早上', english: 'every morning' },
        { word: '歌う', kana: 'うたう', meaning: '唱歌', english: 'to sing; to compose' },
        { word: '体', kana: 'たい', meaning: '身體', english: 'body; physique; shape' },
        { word: '口', kana: 'こう', meaning: '嘴巴；（人數量詞）', english: 'counter for people; mouth' },
        { word: '風', kana: 'かぜ', meaning: '風', english: 'wind; breeze; manner' },

        { word: '借りる', kana: 'かりる', meaning: '借（入）', english: 'to borrow; to rent' },
        { word: '宿題', kana: 'しゅくだい', meaning: '作業', english: 'homework' },
        { word: '封筒', kana: 'ふうとう', meaning: '信封', english: 'envelope' },
        { word: '飲み物', kana: 'のみもの', meaning: '飲料', english: 'drink; beverage' },
        { word: 'あの', kana: 'あの', meaning: '那個（較遠）', english: 'that (distant)' },
        { word: '細い', kana: 'ほそい', meaning: '細的', english: 'thin; slender' },
        { word: '昨夜', kana: 'ゆうべ', meaning: '昨晚', english: 'last night' },
        { word: '晩', kana: 'ばん', meaning: '晚上', english: 'evening' },
        { word: '待つ', kana: 'まつ', meaning: '等待', english: 'to wait' },
        { word: '今朝', kana: 'けさ', meaning: '今天早上', english: 'this morning' },
        { word: '鉛筆', kana: 'えんぴつ', meaning: '鉛筆', english: 'pencil' },
        { word: '傘', kana: 'かさ', meaning: '雨傘', english: 'umbrella' },
        { word: '辺', kana: 'へん', meaning: '附近', english: 'area; vicinity' },
        { word: '火曜日', kana: 'かようび', meaning: '星期二', english: 'Tuesday' },
        { word: '遅い', kana: 'おそい', meaning: '慢的；遲的', english: 'slow; late' },
        { word: '話す', kana: 'はなす', meaning: '說話', english: 'to talk; to speak' },
        { word: '立つ', kana: 'たつ', meaning: '站立', english: 'to stand; to rise' },
        { word: '背広', kana: 'せびろ', meaning: '西裝', english: 'business suit' },
        { word: '七つ', kana: 'ななつ', meaning: '七個', english: 'seven' },
        { word: '赤', kana: 'あか', meaning: '紅色', english: 'red' },
        { word: '甘い', kana: 'あまい', meaning: '甜的', english: 'sweet' },
        { word: 'カップ', kana: 'カップ', meaning: '杯子', english: 'cup' },
        { word: '薄い', kana: 'うすい', meaning: '薄的；淡的', english: 'thin; pale' },
        { word: '貼る', kana: 'はる', meaning: '貼', english: 'to stick; to paste' },
        { word: 'いろいろ', kana: 'いろいろ', meaning: '各種各樣', english: 'various' },
        { word: 'カレンダー', kana: 'カレンダー', meaning: '日曆', english: 'calendar' },
        { word: '乗る', kana: 'のる', meaning: '搭乘', english: 'to get on; to board' },
        { word: '誕生日', kana: 'たんじょうび', meaning: '生日', english: 'birthday' },
        { word: '靴下', kana: 'くつした', meaning: '襪子', english: 'socks' },
        { word: '鶏肉', kana: 'とりにく', meaning: '雞肉', english: 'chicken meat' },
        { word: '始まる', kana: 'はじまる', meaning: '開始', english: 'to begin; to start' },
        { word: '太い', kana: 'ふとい', meaning: '粗的；胖的', english: 'fat; thick' },
        { word: 'クラス', kana: 'クラス', meaning: '班級', english: 'class' },
        { word: '万年筆', kana: 'まんねんひつ', meaning: '鋼筆', english: 'fountain pen' },
        { word: '返す', kana: 'かえす', meaning: '歸還', english: 'to return' },
        { word: '切符', kana: 'きっぷ', meaning: '車票', english: 'ticket' },
        { word: '入れる', kana: 'いれる', meaning: '放入', english: 'to put in; to insert' },
        { word: '忙しい', kana: 'いそがしい', meaning: '忙碌的', english: 'busy' },
        { word: 'トイレ', kana: 'トイレ', meaning: '廁所', english: 'toilet' },
        { word: 'あの', kana: 'あの', meaning: '那個；嗯（發語詞）', english: 'say; well (interjection)' },
        { word: '丸い', kana: 'まるい', meaning: '圓的', english: 'round; circular' },
        { word: '若い', kana: 'わかい', meaning: '年輕的', english: 'young' },
        { word: 'スカート', kana: 'スカート', meaning: '裙子', english: 'skirt' },
        { word: '重い', kana: 'おもい', meaning: '重的', english: 'heavy' },
        { word: 'ノート', kana: 'ノート', meaning: '筆記本', english: 'notebook' },
        { word: '違う', kana: 'ちがう', meaning: '不同；不對', english: 'to differ' },
        { word: 'そこ', kana: 'そこ', meaning: '那裡', english: 'there' },
        { word: '短い', kana: 'みじかい', meaning: '短的', english: 'short' },
        { word: 'じゃあ', kana: 'じゃあ', meaning: '那麼', english: 'then; well' },
        { word: '空', kana: 'そら', meaning: '天空', english: 'sky' },
        { word: '円い', kana: 'まるい', meaning: '圓的', english: 'round; circular' },
        { word: '青い', kana: 'あおい', meaning: '藍色的', english: 'blue; green' },
        { word: '弱い', kana: 'よわい', meaning: '弱的', english: 'weak' },
        { word: '近く', kana: 'ちかく', meaning: '附近', english: 'near; vicinity' },
        { word: '分かる', kana: 'わかる', meaning: '知道；明白', english: 'to understand' },
        { word: '遊ぶ', kana: 'あそぶ', meaning: '玩', english: 'to play' },
        { word: '叔父', kana: 'おじ', meaning: '叔叔（年輕）', english: 'uncle' },
        { word: '本棚', kana: 'ほんだな', meaning: '書架', english: 'bookshelves' },
        { word: '会う', kana: 'あう', meaning: '見面', english: 'to meet' },
        { word: '撮る', kana: 'とる', meaning: '拍（照）', english: 'to take (photo)' },
        { word: '茶碗', kana: 'ちゃわん', meaning: '飯碗', english: 'rice bowl' },
        { word: '暇', kana: 'ひま', meaning: '空閒', english: 'spare time' },
        { word: '毎晩', kana: 'まいばん', meaning: '每晚', english: 'every night' },
        { word: '豚肉', kana: 'ぶたにく', meaning: '豬肉', english: 'pork' },
        { word: '左', kana: 'ひだり', meaning: '左邊', english: 'left' },
        { word: '辛い', kana: 'からい', meaning: '辣的', english: 'spicy; hot' },
        { word: 'どこ', kana: 'どこ', meaning: '哪裡', english: 'where' },
        { word: 'どちら', kana: 'どちら', meaning: '哪一邊', english: 'which way; which one' },
        { word: '休む', kana: 'やすむ', meaning: '休息；請假', english: 'to be absent; to rest' },
        { word: 'レストラン', kana: 'レストラン', meaning: '餐廳', english: 'restaurant' },
        { word: 'テープ', kana: 'テープ', meaning: '錄音帶', english: 'tape' },
        { word: '再来年', kana: 'さらいねん', meaning: '後年', english: 'year after next' },
        { word: '醤油', kana: 'しょうゆ', meaning: '醬油', english: 'soy sauce' },
        { word: 'ドア', kana: 'ドア', meaning: '門', english: 'door' },
        { word: 'フィルム', kana: 'フィルム', meaning: '底片', english: 'film' },
        { word: 'どうぞ', kana: 'どうぞ', meaning: '請', english: 'please' },
        { word: '美味しい', kana: 'おいしい', meaning: '好吃的', english: 'delicious' },
        { word: '座る', kana: 'すわる', meaning: '坐', english: 'to sit' },
        { word: 'あっち', kana: 'あっち', meaning: '那邊', english: 'that way (over there)' },
        { word: 'ポスト', kana: 'ポスト', meaning: '郵筒', english: 'post; postbox' },
        { word: '洗う', kana: 'あらう', meaning: '洗', english: 'to wash' },
        { word: '覚える', kana: 'おぼえる', meaning: '記住', english: 'to memorize' },
        { word: '九つ', kana: 'ここのつ', meaning: '九個', english: 'nine' },
        { word: '悪い', kana: 'わるい', meaning: '不好的', english: 'bad; evil' },
        { word: '曇り', kana: 'くもり', meaning: '陰天', english: 'cloudiness' },
        { word: '三日', kana: 'みっか', meaning: '三號；三天', english: 'the third day; three days' },
        { word: 'あちら', kana: 'あちら', meaning: '那邊', english: 'that way (over there)' },
        { word: '消す', kana: 'けす', meaning: '關掉；消除', english: 'to erase; to turn off' },
        { word: '軽い', kana: 'かるい', meaning: '輕的', english: 'light' },
        { word: '猫', kana: 'ねこ', meaning: '貓', english: 'cat' },
        { word: '東', kana: 'ひがし', meaning: '東', english: 'east' },
        { word: '出かける', kana: 'でかける', meaning: '出門', english: 'to go out' },
        { word: 'どっち', kana: 'どっち', meaning: '哪一邊', english: 'which way; which one' },
        { word: '灰皿', kana: 'はいざら', meaning: '菸灰缸', english: 'ashtray' },
        { word: '冷たい', kana: 'つめたい', meaning: '冷的', english: 'cold' },
        { word: '曲がる', kana: 'まがる', meaning: '轉彎', english: 'to bend; to curve' },
        { word: '泳ぐ', kana: 'およぐ', meaning: '游泳', english: 'to swim' },
        { word: 'やる', kana: 'やる', meaning: '做', english: 'to do; to perform' },
        { word: '八百屋', kana: 'やおや', meaning: '蔬果店', english: 'greengrocer' },
        { word: 'ラジオ', kana: 'ラジオ', meaning: '收音機', english: 'radio' },

        { word: '降る', kana: 'ふる', meaning: '（雨、雪）下', english: 'to precipitate; to fall' },
        { word: '締める', kana: 'しめる', meaning: '繫緊', english: 'to tie; to fasten; to total' },
        { word: '要る', kana: 'いる', meaning: '需要', english: 'to need; to want' },
        { word: '並ぶ', kana: 'ならぶ', meaning: '排隊；排列', english: 'to line up; to rival' },
        { word: '見せる', kana: 'みせる', meaning: '給看', english: 'to show; to display' },
        { word: 'かかる', kana: 'かかる', meaning: '花費（時間/金錢）', english: 'to take (time/money); to hang' },
        { word: 'せっけん', kana: 'せっけん', meaning: '肥皂', english: 'soap' },
        { word: '兄', kana: 'あに', meaning: '哥哥', english: 'elder brother' },
        { word: '起きる', kana: 'おきる', meaning: '起床', english: 'to get up; to wake up' },
        { word: 'しかし', kana: 'しかし', meaning: '但是', english: 'however; but' },
        { word: '小さな', kana: 'ちいさな', meaning: '小的', english: 'small; little; tiny' },
        { word: 'シャワー', kana: 'シャワー', meaning: '淋浴', english: 'shower' },
        { word: '困る', kana: 'こまる', meaning: '困擾', english: 'to be troubled; to be worried' },
        { word: '飲む', kana: 'のむ', meaning: '喝', english: 'to drink; to smoke' },
        { word: '暖かい', kana: 'あたたかい', meaning: '溫暖的', english: 'warm; mild' },
        { word: 'テスト', kana: 'テスト', meaning: '考試', english: 'test' },
        { word: '教える', kana: 'おしえる', meaning: '教', english: 'to teach; to tell' },
        { word: 'ペン', kana: 'ペン', meaning: '筆', english: 'pen' },
        { word: '零', kana: 'れい', meaning: '零', english: 'zero; nought' },
        { word: '五日', kana: 'いつか', meaning: '五號；五天', english: 'fifth day; five days' },
        { word: '二十日', kana: 'はつか', meaning: '二十號；二十天', english: 'twentieth day; twenty days' },
        { word: 'きれい', kana: 'きれい', meaning: '漂亮；乾淨', english: 'pretty; clean; clear' },
        { word: 'どれ', kana: 'どれ', meaning: '哪一個', english: 'which; whichever' },
        { word: 'コピー', kana: 'コピー', meaning: '影印', english: 'copy; photocopy' },
        { word: '閉める', kana: 'しめる', meaning: '關閉', english: 'to close; to shut' },
        { word: 'いくら', kana: 'いくら', meaning: '多少（錢）', english: 'how much?; even' },
        { word: '晴れる', kana: 'はれる', meaning: '放晴', english: 'to clear up; to be sunny' },
        { word: 'グラム', kana: 'グラム', meaning: '公克', english: 'gram; gramme' },
        { word: '入口', kana: 'いりぐち', meaning: '入口', english: 'entrance; entry; gate' },
        { word: 'セーター', kana: 'セーター', meaning: '毛衣', english: 'sweater; jumper' },
        { word: '遠い', kana: 'とおい', meaning: '遠的', english: 'far; distant' },
        { word: 'はい', kana: 'はい', meaning: '是；好', english: 'yes; understood' },
        { word: '厚い', kana: 'あつい', meaning: '厚的', english: 'thick; deep; kind' },
        { word: '背', kana: 'せ', meaning: '身高；背', english: 'height; stature; back; spine' },
        { word: 'たばこ', kana: 'たばこ', meaning: '香菸', english: 'tobacco; cigarette' },
        { word: '四日', kana: 'よっか', meaning: '四號；四天', english: 'fourth day; four days' },
        { word: '答える', kana: 'こたえる', meaning: '回答', english: 'to answer; to reply' },
        { word: 'ネクタイ', kana: 'ネクタイ', meaning: '領帶', english: 'tie; necktie' },
        { word: '帰る', kana: 'かえる', meaning: '回去', english: 'to return; to come home' },
        { word: '今晩', kana: 'こんばん', meaning: '今晚', english: 'tonight; this evening' },
        { word: '上げる', kana: 'あげる', meaning: '舉起；給', english: 'to raise; to elevate; to do up' },
        { word: '疲れる', kana: 'つかれる', meaning: '疲累', english: 'to get tired; to be worn out' },
        { word: '来る', kana: 'くる', meaning: '來', english: 'to come; to approach; to arrive' },
        { word: 'すぐに', kana: 'すぐに', meaning: '馬上', english: 'instantly; immediately; right away' },
        { word: '暑い', kana: 'あつい', meaning: '炎熱的', english: 'hot; warm' },
        { word: '二十歳', kana: 'はたち', meaning: '二十歲', english: '20 years old; twenty' },
        { word: '六日', kana: 'むいか', meaning: '六號；六天', english: 'sixth day; six days' },
        { word: '涼しい', kana: 'すずしい', meaning: '涼爽的', english: 'cool; refreshing; bright' },
        { word: 'プール', kana: 'プール', meaning: '游泳池', english: '(swimming) pool' },
        { word: 'つける', kana: 'つける', meaning: '打開（開關）', english: 'to turn on; to switch on' },
        { word: 'ギター', kana: 'ギター', meaning: '吉他', english: 'guitar' },
        { word: 'だんだん', kana: 'だんだん', meaning: '漸漸地', english: 'gradually; steps; stairs' },
        { word: 'ゆっくり', kana: 'ゆっくり', meaning: '慢慢地', english: 'slowly; at ease; restful' },
        { word: '開く', kana: 'あく', meaning: '打開', english: 'to open; to open (business)' },
        { word: '聞く', kana: 'きく', meaning: '聽；問', english: 'to hear; to listen' },
        { word: 'カレー', kana: 'カレー', meaning: '咖哩', english: 'curry' },
        { word: 'ちょうど', kana: 'ちょうど', meaning: '正好', english: 'exactly; precisely; just' },
        { word: 'ボールペン', kana: 'ボールペン', meaning: '原子筆', english: 'ball-point pen' },
        { word: 'ナイフ', kana: 'ナイフ', meaning: '刀子', english: 'knife' },
        { word: 'そっち', kana: 'そっち', meaning: '那邊', english: 'that way; there' },
        { word: '汚い', kana: 'きたない', meaning: '髒的', english: 'dirty; filthy; messy' },
        { word: '吸う', kana: 'すう', meaning: '吸；抽（菸）', english: 'to smoke; to breathe in; to suck' },
        { word: 'フォーク', kana: 'フォーク', meaning: '叉子', english: 'fork; folk' },
        { word: '消える', kana: 'きえる', meaning: '熄滅；消失', english: 'to go out; to vanish; to disappear' },
        { word: '食堂', kana: 'しょくどう', meaning: '食堂', english: 'dining room; cafeteria; restaurant' },
        { word: 'どうして', kana: 'どうして', meaning: '為什麼', english: 'why?; how?; for what purpose' },
        { word: '貸す', kana: 'かす', meaning: '借出', english: 'to lend; to loan; to rent out' },
        { word: 'ズボン', kana: 'ズボン', meaning: '褲子', english: 'trousers; pants' },
        { word: 'キロ', kana: 'キロ', meaning: '公斤；公里', english: 'kilo-; kilogram' },
        { word: 'スリッパ', kana: 'スリッパ', meaning: '拖鞋', english: 'slipper; slippers' },
        { word: 'メートル', kana: 'メートル', meaning: '公尺', english: 'metre; meter; gauge' },
        { word: '一月', kana: 'ひとつき', meaning: '一個月', english: 'one month' },
        { word: '働く', kana: 'はたらく', meaning: '工作', english: 'to work; to labor; to function' },
        { word: 'それでは', kana: 'それでは', meaning: '那麼', english: 'well then; in that situation' },
        { word: 'マッチ', kana: 'マッチ', meaning: '火柴', english: 'match (contest); to match with' },
        { word: '寒い', kana: 'さむい', meaning: '寒冷的', english: 'cold; uninteresting; lame' },
        { word: 'ええ', kana: 'ええ', meaning: '是', english: 'yes; that is correct' },
        { word: 'タクシー', kana: 'タクシー', meaning: '計程車', english: 'taxi' },
        { word: 'アパート', kana: 'アパート', meaning: '公寓', english: 'apartment building; apartment' },
        { word: 'そちら', kana: 'そちら', meaning: '那邊', english: 'that way; there' },
        { word: 'レコード', kana: 'レコード', meaning: '唱片；紀錄', english: 'record (LP); record (athletics)' },
        { word: 'それから', kana: 'それから', meaning: '然後', english: 'and then; after that' },
        { word: '日曜日', kana: 'にちようび', meaning: '星期日', english: 'Sunday' },
        { word: 'お酒', kana: 'おさけ', meaning: '酒', english: 'alcohol; sake' },
        { word: '半分', kana: 'はんぶん', meaning: '一半', english: 'half' },
        { word: 'お風呂', kana: 'おふろ', meaning: '洗澡；浴室', english: 'bath; bathtub; bathroom' },
        { word: '暗い', kana: 'くらい', meaning: '暗的', english: 'dark; gloomy; dull' },
        { word: '危ない', kana: 'あぶない', meaning: '危險的', english: 'dangerous; risky; critical' },
        { word: 'もう一度', kana: 'もういちど', meaning: '再一次', english: 'once more; again' },
        { word: '死ぬ', kana: 'しぬ', meaning: '死', english: 'to die; to pass away; to lose spirit' },
        { word: 'お姉さん', kana: 'おねえさん', meaning: '姊姊', english: 'elder sister; young lady' },
        { word: '生まれる', kana: 'うまれる', meaning: '出生', english: 'to be born; to be produced' },
        { word: 'お弁当', kana: 'おべんとう', meaning: '便當', english: 'bento; Japanese box lunch' },
        { word: 'コップ', kana: 'コップ', meaning: '玻璃杯', english: 'glass (drinking vessel); tumbler' },
        { word: '渡る', kana: 'わたる', meaning: '穿越；橫渡', english: 'to cross over; to extend; to span' },
        { word: 'バター', kana: 'バター', meaning: '奶油', english: 'butter' },
        { word: 'どうも', kana: 'どうも', meaning: '謝謝；非常', english: 'thanks; much; very; quite' },
        { word: 'ハンカチ', kana: 'ハンカチ', meaning: '手帕', english: 'handkerchief' },
        { word: 'スプーン', kana: 'スプーン', meaning: '湯匙', english: 'spoon' },
        { word: '一昨日', kana: 'おととい', meaning: '前天', english: 'day before yesterday' },

        { word: 'こっち', kana: 'こっち', meaning: '這邊', english: 'this way; here' },
        { word: 'あめ', kana: 'あめ', meaning: '糖果', english: 'candy; rice-sugar' },
        { word: 'おまわりさん', kana: 'おまわりさん', meaning: '警察先生', english: 'police officer' },
        { word: '住む', kana: 'すむ', meaning: '居住', english: 'to live; to reside' },
        { word: '歩く', kana: 'あるく', meaning: '走路', english: 'to walk' },
        { word: 'ストーブ', kana: 'ストーブ', meaning: '暖爐', english: 'heater; stove' },
        { word: 'おなか', kana: 'おなか', meaning: '肚子', english: 'stomach' },
        { word: 'エレベーター', kana: 'エレベーター', meaning: '電梯', english: 'elevator; lift' },
        { word: 'そうして', kana: 'そうして', meaning: '然後；那樣', english: 'and; like that' },
        { word: '土曜日', kana: 'どようび', meaning: '星期六', english: 'Saturday' },
        { word: '置く', kana: 'おく', meaning: '放置', english: 'to put; to place' },
        { word: 'あそこ', kana: 'あそこ', meaning: '那裡', english: 'there; that place' },
        { word: '夕飯', kana: 'ゆうはん', meaning: '晚餐', english: 'evening meal' },
        { word: '黄色い', kana: 'きいろい', meaning: '黃色的', english: 'yellow' },
        { word: 'さあ', kana: 'さあ', meaning: '來吧；嗯', english: 'come; well' },
        { word: 'デパート', kana: 'デパート', meaning: '百貨公司', english: 'department store' },
        { word: '習う', kana: 'ならう', meaning: '學習', english: 'to take lessons; to learn' },
        { word: '履く', kana: 'はく', meaning: '穿（鞋、褲）', english: 'to put on footwear' },
        { word: 'どなた', kana: 'どなた', meaning: '哪位', english: 'who?' },
        { word: '引く', kana: 'ひく', meaning: '拉', english: 'to pull; to draw' },
        { word: '奥さん', kana: 'おくさん', meaning: '太太；夫人', english: 'wife; madam' },
        { word: '開ける', kana: 'あける', meaning: '打開', english: 'to open' },
        { word: '差す', kana: 'さす', meaning: '照射；撐（傘）', english: 'to shine; to be visible' },
        { word: 'ワイシャツ', kana: 'ワイシャツ', meaning: '襯衫', english: 'shirt; dress shirt' },
        { word: '居る', kana: 'いる', meaning: '在（有生物）', english: 'to be; to exist' },
        { word: '月曜日', kana: 'げつようび', meaning: '星期一', english: 'Monday' },
        { word: 'お菓子', kana: 'おかし', meaning: '點心；零食', english: 'confections; sweets' },
        { word: '金曜日', kana: 'きんようび', meaning: '星期五', english: 'Friday' },
        { word: 'おばあさん', kana: 'おばあさん', meaning: '奶奶；老婦人', english: 'grandmother; old woman' },
        { word: '飛ぶ', kana: 'とぶ', meaning: '飛；跳', english: 'to fly; to jump' },
        { word: 'まっすぐ', kana: 'まっすぐ', meaning: '直直地', english: 'straight; direct' },
        { word: 'まずい', kana: 'まずい', meaning: '難吃的', english: 'unappetizing; unskillful' },
        { word: 'ご飯', kana: 'ごはん', meaning: '飯', english: 'cooked rice; meal' },
        { word: 'つまらない', kana: 'つまらない', meaning: '無聊的', english: 'dull; trivial' },
        { word: '水曜日', kana: 'すいようび', meaning: '星期三', english: 'Wednesday' },
        { word: '狭い', kana: 'せまい', meaning: '狹窄的', english: 'narrow; confined' },
        { word: '易しい', kana: 'やさしい', meaning: '簡單的', english: 'easy; simple' },
        { word: '六つ', kana: 'むっつ', meaning: '六個', english: 'six' },
        { word: '着く', kana: 'つく', meaning: '到達', english: 'to arrive; to sit on' },
        { word: 'テープレコーダー', kana: 'テープレコーダー', meaning: '錄音機', english: 'tape recorder' },
        { word: '脱ぐ', kana: 'ぬぐ', meaning: '脫（衣服）', english: 'to take off clothes' },
        { word: '八つ', kana: 'やっつ', meaning: '八個', english: 'eight' },
        { word: '閉まる', kana: 'しまる', meaning: '關閉', english: 'to be shut; to close' },
        { word: '木曜日', kana: 'もくようび', meaning: '星期四', english: 'Thursday' },
        { word: '葉書', kana: 'はがき', meaning: '明信片', english: 'postcard; note' },
        { word: '明後日', kana: 'あさって', meaning: '後天', english: 'day after tomorrow' },
        { word: 'ラジカセ', kana: 'ラジカセ', meaning: '收錄音機', english: 'radio-cassette player' },
        { word: '花瓶', kana: 'かびん', meaning: '花瓶', english: 'flower vase' },
        { word: 'キログラム', kana: 'キログラム', meaning: '公斤', english: 'kilogram' },
        { word: 'お兄さん', kana: 'おにいさん', meaning: '哥哥', english: 'older brother' },
        { word: '登る', kana: 'のぼる', meaning: '爬（山）', english: 'to ascend; to climb' },
        { word: 'キロメートル', kana: 'キロメートル', meaning: '公里', english: 'kilometer' },
        { word: '忘れる', kana: 'わすれる', meaning: '忘記', english: 'to forget' },
        { word: '無くす', kana: 'なくす', meaning: '遺失', english: 'to lose; to get rid of' },
        { word: '咲く', kana: 'さく', meaning: '（花）開', english: 'to bloom' },
        { word: '並べる', kana: 'ならべる', meaning: '排列', english: 'to line up; to arrange' },
        { word: '吹く', kana: 'ふく', meaning: '吹', english: 'to blow' },
        { word: 'ラジオカセット', kana: 'ラジオカセット', meaning: '收錄音機', english: 'radio-cassette; tape recorder' },
        { word: '弾く', kana: 'ひく', meaning: '彈奏', english: 'to play piano/guitar' },
        { word: '勤める', kana: 'つとめる', meaning: '任職', english: 'to work for; to serve as' },
        { word: '鳴く', kana: 'なく', meaning: '（動物）叫', english: 'to sing; to bark' },
        { word: 'お皿', kana: 'おさら', meaning: '盤子', english: 'plate; dish' },
        { word: '晩御飯', kana: 'ばんごはん', meaning: '晚餐', english: 'dinner; evening meal' },
        { word: '叔父', kana: 'おじ', meaning: '叔叔', english: 'uncle' },
        { word: '磨く', kana: 'みがく', meaning: '刷（牙）；擦亮', english: 'to polish; to brush' },
        { word: '昼御飯', kana: 'ひるごはん', meaning: '午餐', english: 'lunch' },
        { word: '朝御飯', kana: 'あさごはん', meaning: '早餐', english: 'breakfast' },
        { word: 'お手洗い', kana: 'おてあらい', meaning: '洗手間', english: 'toilet; restroom' },
        { word: '叔母さん', kana: 'おばさん', meaning: '阿姨', english: 'aunt; old lady' },
        { word: '温い', kana: 'ぬるい', meaning: '微溫的', english: 'lukewarm; lenient' },
        { word: '伯母さん', kana: 'おばさん', meaning: '姑姑；阿姨', english: 'aunt; old lady' },
        { word: '曇る', kana: 'くもる', meaning: '轉陰', english: 'to get cloudy; to cloud over' },
        { word: '賑やか', kana: 'にぎやか', meaning: '熱鬧', english: 'bustling; lively' },
        { word: '字引', kana: 'じびき', meaning: '字典', english: 'dictionary' },
        { word: '煩い', kana: 'うるさい', meaning: '吵鬧的', english: 'noisy; annoying' }
    ]
};
