/* ===== Privacy page translations =====
   privacy.html carries the Traditional Chinese text as its default markup;
   this swaps every [data-p] element for the language picked on the main
   site (localStorage['site_lang']). Only privacy.html loads this file, so
   the main page doesn't pay for eight copies of the policy. Keep the
   sections in step with the zh markup when the policy changes. */
const PRIVACY = {
    'zh-Hans': {
        doc_title: `隐私政策 | Hanabiの小天地`,
        doc_desc: `Hanabiの小天地 隐私政策`,
        back: `← 返回首页`,
        title: `隐私政策`,
        updated: `最后更新：2026 年 9 月`,
        intro: `「Hanabiの小天地」（以下称「本网站」）是一个个人经营的静态网站，提供语言单词测验、音乐播放、留言板等功能。本页说明本网站会用到哪些数据、通过哪些第三方服务，以及你可以如何管理自己的数据。`,
        s1_h: `一、浏览器本地存储（localStorage）`,
        s1_p1: `以下数据只会存储在你自己设备的浏览器中，不会发送到本网站的服务器：`,
        s1_li1: `主题（深色／浅色）与语言偏好设置`,
        s1_li2: `单词测验记录、错题本、已掌握的单词卡状态`,
        s1_li3: `记事本内容（如果使用「记事本」功能）`,
        s1_p2: `清除浏览器数据、更换设备或使用无痕模式，都会让上述内容消失。这些数据完全保存在你的设备上，本网站无法读取或访问。`,
        s2_h: `二、留言板`,
        s2_p: `使用留言板功能时，你填写的昵称与留言内容会通过 Google Apps Script 发送并存储到本网站管理者的 Google 表格中，并会公开显示给所有访客。请勿在留言中填写真实姓名、联系方式等个人敏感信息。`,
        s3_h: `三、建议&改进`,
        s3_p: `在「建议&改进」页面提交的内容，会通过 Google Apps Script 发送并存储到只有本网站管理者能看到的 Google 表格中，不会公开显示。提交时会一并记录当时的网站语言与页面路径，以便了解建议的情境；除此之外不会记录其他数据，除非你自己写在内容里。`,
        s4_h: `四、使用的第三方服务`,
        th_service: `服务`, th_purpose: `用途`, th_data: `可能涉及的数据`,
        r1_purpose: `留言板与「建议&改进」的存储与读取`,
        r1_data: `你主动填写的昵称、留言与建议内容`,
        r2_purpose: `网站访客人数统计`,
        r2_data: `匿名访问次数`,
        r3_purpose: `根据 IP 地址推测所在城市，显示天气小工具（需点击「显示天气」按钮主动开启，不会自动执行）`,
        r3_data: `IP 地址（仅用于推测地理位置，不会存储）`,
        r4_purpose: `提供天气信息`,
        r4_data: `经纬度坐标（来自上方的 IP 定位）`,
        r5_service: `Google AdSense（规划中）`,
        r5_purpose: `显示广告以支持网站运营`,
        r5_data: `可能使用 Cookie 进行广告个性化，详见下方说明`,
        r6_purpose: `赞助／小额支持链接`,
        r6_data: `仅在你主动点击赞助按钮、离开本网站前往 ko-fi.com 后才适用，由 Ko-fi 自行处理`,
        s5_h: `五、广告与 Cookie`,
        s5_p: `本网站可能使用 Google AdSense 显示广告以维持运营成本。Google 及其合作伙伴可能会使用 Cookie，根据你过去访问本网站或其他网站的记录，显示个性化广告。`,
        s5_li1: `你可以前往 <a href="https://myaccount.google.com/data-and-privacy" target="_blank" rel="noopener noreferrer">Google 账号设置</a> 调整广告个性化选项。`,
        s5_li2: `想了解 Google 如何使用数据，可参考 <a href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer">Google 广告技术说明</a>。`,
        s6_h: `六、你的选择`,
        s6_p: `你可以随时通过浏览器设置清除本网站的 localStorage 数据；如果不希望留言公开显示，可以不使用留言板功能；如果不希望天气小工具推测所在城市，可以忽略该小工具（不影响其他功能的使用）。`,
        s7_h: `七、政策更新`,
        s7_p: `本政策可能随网站功能调整而更新，变更时会直接反映在本页面上，不会另行通知。建议偶尔回来查看最新版本。`,
        s8_h: `八、联系方式`,
        s8_p: `如果对本政策有任何疑问，欢迎发邮件给我：<a href="mailto:azusawakohane12@gmail.com">azusawakohane12@gmail.com</a>`,
    },
    en: {
        doc_title: `Privacy Policy | Hanabiの小天地`,
        doc_desc: `Hanabiの小天地 Privacy Policy`,
        back: `← Back to home`,
        title: `Privacy Policy`,
        updated: `Last updated: September 2026`,
        intro: `"Hanabiの小天地" (the "Site") is a personally run static website offering vocabulary quizzes, music playback, a guestbook and more. This page explains what data the Site uses, which third-party services it relies on, and how you can manage your own data.`,
        s1_h: `1. Local browser storage (localStorage)`,
        s1_p1: `The following data is stored only in the browser on your own device and is never sent to the Site's servers:`,
        s1_li1: `Theme (dark / light) and language preferences`,
        s1_li2: `Quiz history, the mistake notebook, and which flashcards you have learned`,
        s1_li3: `Notepad contents (if you use the Notepad feature)`,
        s1_p2: `Clearing your browser data, switching devices or using private browsing will erase all of the above. This data stays entirely on your device; the Site cannot read or access it.`,
        s2_h: `2. Guestbook`,
        s2_p: `When you use the guestbook, the nickname and message you enter are sent via Google Apps Script and stored in a Google Sheet owned by the Site's administrator, and they are shown publicly to every visitor. Please do not include your real name, contact details or other sensitive personal information in a message.`,
        s3_h: `3. Suggestions`,
        s3_p: `Anything you submit on the "Suggestions" page is sent via Google Apps Script and stored in a Google Sheet that only the Site's administrator can see; it is never shown publicly. The Site's language and the page path at the time of submission are recorded with it, to give the suggestion some context. Nothing else is recorded unless you write it in your message yourself.`,
        s4_h: `4. Third-party services`,
        th_service: `Service`, th_purpose: `Purpose`, th_data: `Data that may be involved`,
        r1_purpose: `Storing and reading guestbook messages and suggestions`,
        r1_data: `The nickname, messages and suggestions you choose to enter`,
        r2_purpose: `Counting site visits`,
        r2_data: `Anonymous visit count`,
        r3_purpose: `Estimating your city from your IP address for the weather widget (only after you click "Show weather"; it never runs on its own)`,
        r3_data: `IP address (used only to estimate location, not stored)`,
        r4_purpose: `Providing weather information`,
        r4_data: `Latitude and longitude (from the IP lookup above)`,
        r5_service: `Google AdSense (planned)`,
        r5_purpose: `Showing ads to support the Site`,
        r5_data: `May use cookies to personalise ads; see below`,
        r6_purpose: `Donation / tip link`,
        r6_data: `Applies only after you click the support button and leave for ko-fi.com; handled by Ko-fi itself`,
        s5_h: `5. Advertising and cookies`,
        s5_p: `The Site may use Google AdSense to show ads that help cover its running costs. Google and its partners may use cookies to show personalised ads based on your past visits to this and other websites.`,
        s5_li1: `You can adjust ad personalisation in your <a href="https://myaccount.google.com/data-and-privacy" target="_blank" rel="noopener noreferrer">Google Account settings</a>.`,
        s5_li2: `To learn how Google uses data, see <a href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer">How Google uses cookies in advertising</a>.`,
        s6_h: `6. Your choices`,
        s6_p: `You can clear the Site's localStorage data at any time through your browser settings. If you don't want a message shown publicly, simply don't use the guestbook. If you don't want the weather widget to estimate your city, just leave it off; every other feature works without it.`,
        s7_h: `7. Changes to this policy`,
        s7_p: `This policy may be updated as the Site's features change. Changes are made directly on this page without separate notice, so please check back from time to time.`,
        s8_h: `8. Contact`,
        s8_p: `If you have any questions about this policy, feel free to email me: <a href="mailto:azusawakohane12@gmail.com">azusawakohane12@gmail.com</a>`,
    },
    ja: {
        doc_title: `プライバシーポリシー | Hanabiの小天地`,
        doc_desc: `Hanabiの小天地 プライバシーポリシー`,
        back: `← ホームに戻る`,
        title: `プライバシーポリシー`,
        updated: `最終更新：2026年9月`,
        intro: `「Hanabiの小天地」（以下「本サイト」）は、個人が運営する静的なウェブサイトで、語学の単語テスト、音楽再生、掲示板などの機能を提供しています。このページでは、本サイトが使用するデータ、利用している第三者サービス、そしてご自身のデータを管理する方法について説明します。`,
        s1_h: `1. ブラウザのローカルストレージ（localStorage）`,
        s1_p1: `以下のデータはお使いの端末のブラウザ内にのみ保存され、本サイトのサーバーに送信されることはありません：`,
        s1_li1: `テーマ（ダーク／ライト）と言語の設定`,
        s1_li2: `単語テストの記録、間違いノート、覚えた単語カードの状態`,
        s1_li3: `メモ帳の内容（「メモ帳」機能を使った場合）`,
        s1_p2: `ブラウザのデータを消去したり、端末を変えたり、シークレットモードを使ったりすると、上記の内容は消えます。これらのデータはすべてお使いの端末内にあり、本サイトが読み取ったりアクセスしたりすることはできません。`,
        s2_h: `2. 掲示板`,
        s2_p: `掲示板を利用すると、入力したニックネームとメッセージは Google Apps Script を通じて本サイト管理者の Google スプレッドシートに送信・保存され、すべての訪問者に公開表示されます。本名や連絡先など、個人を特定できる情報は書き込まないでください。`,
        s3_h: `3. ご意見&改善`,
        s3_p: `「ご意見&改善」ページから送信した内容は、Google Apps Script を通じて本サイト管理者だけが閲覧できる Google スプレッドシートに送信・保存され、公開されることはありません。送信時には、内容の背景を知るために、その時点のサイトの言語とページのパスもあわせて記録されます。ご自身で内容に書かない限り、それ以外の情報は記録されません。`,
        s4_h: `4. 利用している第三者サービス`,
        th_service: `サービス`, th_purpose: `用途`, th_data: `関係する可能性のあるデータ`,
        r1_purpose: `掲示板と「ご意見&改善」の保存・読み込み`,
        r1_data: `ご自身で入力したニックネーム、メッセージ、ご意見`,
        r2_purpose: `サイトの訪問者数の集計`,
        r2_data: `匿名の訪問回数`,
        r3_purpose: `IP アドレスからおおよその都市を推定し、天気ウィジェットを表示（「天気を表示」ボタンを押したときのみ動作し、自動では実行されません）`,
        r3_data: `IP アドレス（位置の推定にのみ使用し、保存しません）`,
        r4_purpose: `天気情報の提供`,
        r4_data: `緯度・経度（上記の IP 位置推定によるもの）`,
        r5_service: `Google AdSense（導入予定）`,
        r5_purpose: `サイト運営を支える広告の表示`,
        r5_data: `広告のパーソナライズに Cookie が使われる場合があります（下記参照）`,
        r6_purpose: `寄付／支援用リンク`,
        r6_data: `支援ボタンをクリックして本サイトを離れ、ko-fi.com に移動した後にのみ該当し、Ko-fi が独自に取り扱います`,
        s5_h: `5. 広告と Cookie`,
        s5_p: `本サイトでは、運営費をまかなうために Google AdSense による広告を表示する場合があります。Google およびそのパートナーは Cookie を使用し、本サイトや他のサイトへの過去の訪問履歴に基づいてパーソナライズされた広告を表示することがあります。`,
        s5_li1: `広告のパーソナライズは <a href="https://myaccount.google.com/data-and-privacy" target="_blank" rel="noopener noreferrer">Google アカウントの設定</a> で変更できます。`,
        s5_li2: `Google によるデータの使用方法については <a href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer">Google の広告に関する説明</a> をご覧ください。`,
        s6_h: `6. ご自身で選べること`,
        s6_p: `本サイトの localStorage データは、ブラウザの設定からいつでも消去できます。メッセージを公開したくない場合は掲示板を使わなければ大丈夫です。天気ウィジェットに都市を推定されたくない場合は、ウィジェットを使わなくても他の機能には影響ありません。`,
        s7_h: `7. ポリシーの更新`,
        s7_p: `本ポリシーはサイトの機能変更にあわせて更新されることがあります。変更はこのページに直接反映され、個別のお知らせは行いません。ときどき最新版をご確認ください。`,
        s8_h: `8. お問い合わせ`,
        s8_p: `本ポリシーについてご質問があれば、お気軽にメールでどうぞ：<a href="mailto:azusawakohane12@gmail.com">azusawakohane12@gmail.com</a>`,
    },
    ko: {
        doc_title: `개인정보 처리방침 | Hanabiの小天地`,
        doc_desc: `Hanabiの小天地 개인정보 처리방침`,
        back: `← 홈으로 돌아가기`,
        title: `개인정보 처리방침`,
        updated: `최종 업데이트: 2026년 9월`,
        intro: `「Hanabiの小天地」(이하 "본 사이트")는 개인이 운영하는 정적 웹사이트로, 외국어 단어 테스트, 음악 재생, 방명록 등의 기능을 제공합니다. 이 페이지에서는 본 사이트가 어떤 데이터를 사용하는지, 어떤 제3자 서비스를 이용하는지, 그리고 여러분이 자신의 데이터를 어떻게 관리할 수 있는지 설명합니다.`,
        s1_h: `1. 브라우저 로컬 저장소(localStorage)`,
        s1_p1: `다음 데이터는 여러분의 기기 브라우저에만 저장되며, 본 사이트의 서버로 전송되지 않습니다:`,
        s1_li1: `테마(다크/라이트)와 언어 설정`,
        s1_li2: `단어 테스트 기록, 오답 노트, 외운 단어 카드 상태`,
        s1_li3: `메모장 내용("메모장" 기능을 사용하는 경우)`,
        s1_p2: `브라우저 데이터를 삭제하거나, 기기를 바꾸거나, 시크릿 모드를 사용하면 위의 내용은 모두 사라집니다. 이 데이터는 전적으로 여러분의 기기에 있으며, 본 사이트는 이를 읽거나 접근할 수 없습니다.`,
        s2_h: `2. 방명록`,
        s2_p: `방명록을 이용하면 입력한 닉네임과 메시지가 Google Apps Script를 통해 본 사이트 관리자의 Google 스프레드시트로 전송·저장되며, 모든 방문자에게 공개됩니다. 실명, 연락처 등 민감한 개인정보는 적지 말아 주세요.`,
        s3_h: `3. 제안&개선`,
        s3_p: `"제안&개선" 페이지에서 보낸 내용은 Google Apps Script를 통해 본 사이트 관리자만 볼 수 있는 Google 스프레드시트로 전송·저장되며, 공개되지 않습니다. 제안의 맥락을 알기 위해 보낼 당시의 사이트 언어와 페이지 경로도 함께 기록됩니다. 직접 내용에 적지 않는 한, 그 밖의 정보는 기록되지 않습니다.`,
        s4_h: `4. 이용하는 제3자 서비스`,
        th_service: `서비스`, th_purpose: `용도`, th_data: `관련될 수 있는 데이터`,
        r1_purpose: `방명록과 "제안&개선" 내용의 저장 및 불러오기`,
        r1_data: `직접 입력한 닉네임, 메시지, 제안 내용`,
        r2_purpose: `사이트 방문자 수 집계`,
        r2_data: `익명 방문 횟수`,
        r3_purpose: `IP 주소로 도시를 추정해 날씨 위젯 표시("날씨 표시" 버튼을 눌렀을 때만 작동하며, 자동으로 실행되지 않음)`,
        r3_data: `IP 주소(위치 추정에만 사용하며 저장하지 않음)`,
        r4_purpose: `날씨 정보 제공`,
        r4_data: `위도·경도 좌표(위의 IP 위치 추정 결과)`,
        r5_service: `Google AdSense(도입 예정)`,
        r5_purpose: `사이트 운영을 위한 광고 표시`,
        r5_data: `광고 맞춤 설정에 쿠키가 사용될 수 있음(아래 참고)`,
        r6_purpose: `후원 링크`,
        r6_data: `후원 버튼을 눌러 본 사이트를 떠나 ko-fi.com으로 이동한 뒤에만 해당하며, Ko-fi가 자체적으로 처리함`,
        s5_h: `5. 광고와 쿠키`,
        s5_p: `본 사이트는 운영비를 충당하기 위해 Google AdSense 광고를 표시할 수 있습니다. Google과 그 파트너는 쿠키를 사용해, 여러분이 본 사이트나 다른 웹사이트를 방문한 기록을 바탕으로 맞춤 광고를 표시할 수 있습니다.`,
        s5_li1: `<a href="https://myaccount.google.com/data-and-privacy" target="_blank" rel="noopener noreferrer">Google 계정 설정</a>에서 광고 맞춤 설정을 변경할 수 있습니다.`,
        s5_li2: `Google의 데이터 사용 방식은 <a href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer">Google 광고 기술 안내</a>를 참고하세요.`,
        s6_h: `6. 여러분의 선택`,
        s6_p: `브라우저 설정에서 언제든지 본 사이트의 localStorage 데이터를 삭제할 수 있습니다. 메시지가 공개되는 것을 원하지 않으면 방명록을 이용하지 않으면 됩니다. 날씨 위젯이 도시를 추정하는 것을 원하지 않으면 위젯을 켜지 않아도 되며, 다른 기능에는 영향이 없습니다.`,
        s7_h: `7. 방침 변경`,
        s7_p: `본 방침은 사이트 기능이 바뀌면 함께 업데이트될 수 있으며, 변경 사항은 별도 공지 없이 이 페이지에 바로 반영됩니다. 가끔 최신 버전을 확인해 주세요.`,
        s8_h: `8. 연락처`,
        s8_p: `본 방침에 대해 궁금한 점이 있으면 언제든지 메일 주세요: <a href="mailto:azusawakohane12@gmail.com">azusawakohane12@gmail.com</a>`,
    },
    ru: {
        doc_title: `Политика конфиденциальности | Hanabiの小天地`,
        doc_desc: `Hanabiの小天地 — политика конфиденциальности`,
        back: `← На главную`,
        title: `Политика конфиденциальности`,
        updated: `Последнее обновление: сентябрь 2026 г.`,
        intro: `«Hanabiの小天地» (далее — «Сайт») — статический сайт, который ведёт частное лицо. На нём есть тесты по словарному запасу, музыкальный плеер, гостевая книга и другие функции. На этой странице объясняется, какие данные использует Сайт, какими сторонними сервисами он пользуется и как вы можете управлять своими данными.`,
        s1_h: `1. Локальное хранилище браузера (localStorage)`,
        s1_p1: `Следующие данные хранятся только в браузере на вашем устройстве и никогда не отправляются на серверы Сайта:`,
        s1_li1: `Тема (тёмная / светлая) и выбранный язык`,
        s1_li2: `История тестов, тетрадь ошибок и выученные карточки`,
        s1_li3: `Содержимое заметок (если вы пользуетесь «Заметками»)`,
        s1_p2: `Если очистить данные браузера, сменить устройство или открыть сайт в режиме инкогнито, всё перечисленное исчезнет. Эти данные находятся только на вашем устройстве — Сайт не может их прочитать или получить к ним доступ.`,
        s2_h: `2. Гостевая книга`,
        s2_p: `Когда вы пишете в гостевую книгу, указанные вами имя и сообщение отправляются через Google Apps Script и сохраняются в Google Таблице администратора Сайта, а затем публично показываются всем посетителям. Пожалуйста, не указывайте в сообщениях настоящее имя, контакты и другие личные данные.`,
        s3_h: `3. Предложения`,
        s3_p: `Всё, что вы отправляете на странице «Предложения», передаётся через Google Apps Script и сохраняется в Google Таблице, которую видит только администратор Сайта; публично это не показывается. Вместе с сообщением записываются язык Сайта и путь страницы на момент отправки — чтобы понимать контекст предложения. Ничего другого не записывается, если только вы сами не укажете это в тексте.`,
        s4_h: `4. Сторонние сервисы`,
        th_service: `Сервис`, th_purpose: `Назначение`, th_data: `Какие данные могут затрагиваться`,
        r1_purpose: `Хранение и загрузка записей гостевой книги и предложений`,
        r1_data: `Имя, сообщения и предложения, которые вы вводите сами`,
        r2_purpose: `Подсчёт посещений сайта`,
        r2_data: `Анонимное число посещений`,
        r3_purpose: `Определение города по IP-адресу для виджета погоды (только после нажатия «Показать погоду»; сам по себе не запускается)`,
        r3_data: `IP-адрес (используется только для определения местоположения и не сохраняется)`,
        r4_purpose: `Данные о погоде`,
        r4_data: `Широта и долгота (по результату определения по IP выше)`,
        r5_service: `Google AdSense (планируется)`,
        r5_purpose: `Показ рекламы для поддержки Сайта`,
        r5_data: `Могут использоваться файлы cookie для персонализации рекламы — см. ниже`,
        r6_purpose: `Ссылка для поддержки / пожертвований`,
        r6_data: `Действует только после того, как вы нажмёте кнопку поддержки и перейдёте на ko-fi.com; данные обрабатывает сам Ko-fi`,
        s5_h: `5. Реклама и файлы cookie`,
        s5_p: `Сайт может показывать рекламу Google AdSense, чтобы покрывать расходы на работу. Google и его партнёры могут использовать файлы cookie, чтобы показывать персонализированную рекламу на основе ваших прошлых посещений этого и других сайтов.`,
        s5_li1: `Настроить персонализацию рекламы можно в <a href="https://myaccount.google.com/data-and-privacy" target="_blank" rel="noopener noreferrer">настройках аккаунта Google</a>.`,
        s5_li2: `О том, как Google использует данные, читайте в <a href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer">описании рекламных технологий Google</a>.`,
        s6_h: `6. Ваш выбор`,
        s6_p: `Вы можете в любой момент удалить данные localStorage этого Сайта в настройках браузера. Если не хотите, чтобы ваше сообщение было видно всем, просто не пользуйтесь гостевой книгой. Если не хотите, чтобы виджет погоды определял ваш город, не включайте его — остальные функции работают и без него.`,
        s7_h: `7. Изменения политики`,
        s7_p: `Эта политика может обновляться вместе с функциями Сайта. Изменения вносятся прямо на эту страницу без отдельного уведомления, поэтому иногда заглядывайте сюда.`,
        s8_h: `8. Контакты`,
        s8_p: `Если у вас есть вопросы об этой политике, пишите мне: <a href="mailto:azusawakohane12@gmail.com">azusawakohane12@gmail.com</a>`,
    },
    fr: {
        doc_title: `Politique de confidentialité | Hanabiの小天地`,
        doc_desc: `Hanabiの小天地 – Politique de confidentialité`,
        back: `← Retour à l'accueil`,
        title: `Politique de confidentialité`,
        updated: `Dernière mise à jour : septembre 2026`,
        intro: `« Hanabiの小天地 » (ci-après « le Site ») est un site statique tenu par un particulier, qui propose des quiz de vocabulaire, un lecteur de musique, un livre d'or et d'autres fonctions. Cette page explique quelles données le Site utilise, à quels services tiers il fait appel et comment vous pouvez gérer vos propres données.`,
        s1_h: `1. Stockage local du navigateur (localStorage)`,
        s1_p1: `Les données suivantes sont enregistrées uniquement dans le navigateur de votre appareil et ne sont jamais envoyées aux serveurs du Site :`,
        s1_li1: `Le thème (sombre / clair) et la langue choisie`,
        s1_li2: `L'historique des quiz, le carnet d'erreurs et les cartes déjà apprises`,
        s1_li3: `Le contenu du bloc-notes (si vous utilisez cette fonction)`,
        s1_p2: `Effacer les données de votre navigateur, changer d'appareil ou utiliser la navigation privée fera disparaître tout ce qui précède. Ces données restent entièrement sur votre appareil ; le Site ne peut ni les lire ni y accéder.`,
        s2_h: `2. Livre d'or`,
        s2_p: `Lorsque vous utilisez le livre d'or, le pseudo et le message que vous saisissez sont envoyés via Google Apps Script et enregistrés dans une feuille Google Sheets appartenant à l'administrateur du Site, puis affichés publiquement pour tous les visiteurs. Merci de ne pas indiquer votre vrai nom, vos coordonnées ou d'autres informations personnelles sensibles.`,
        s3_h: `3. Suggestions`,
        s3_p: `Ce que vous envoyez depuis la page « Suggestions » est transmis via Google Apps Script et enregistré dans une feuille Google Sheets que seul l'administrateur du Site peut consulter ; rien n'est affiché publiquement. La langue du Site et le chemin de la page au moment de l'envoi sont enregistrés avec le message, pour en comprendre le contexte. Rien d'autre n'est enregistré, sauf ce que vous écrivez vous-même dans le message.`,
        s4_h: `4. Services tiers utilisés`,
        th_service: `Service`, th_purpose: `Utilisation`, th_data: `Données éventuellement concernées`,
        r1_purpose: `Enregistrement et lecture du livre d'or et des suggestions`,
        r1_data: `Le pseudo, les messages et les suggestions que vous saisissez vous-même`,
        r2_purpose: `Comptage des visites du site`,
        r2_data: `Nombre de visites anonyme`,
        r3_purpose: `Estimation de votre ville à partir de l'adresse IP pour le widget météo (uniquement après un clic sur « Afficher la météo » ; jamais de façon automatique)`,
        r3_data: `Adresse IP (utilisée seulement pour estimer la position, non conservée)`,
        r4_purpose: `Fourniture des données météo`,
        r4_data: `Latitude et longitude (issues de la localisation IP ci-dessus)`,
        r5_service: `Google AdSense (prévu)`,
        r5_purpose: `Affichage de publicités pour soutenir le Site`,
        r5_data: `Peut utiliser des cookies pour personnaliser les annonces ; voir ci-dessous`,
        r6_purpose: `Lien de soutien / dons`,
        r6_data: `Ne s'applique qu'après un clic sur le bouton de soutien et votre départ vers ko-fi.com ; géré par Ko-fi lui-même`,
        s5_h: `5. Publicité et cookies`,
        s5_p: `Le Site peut utiliser Google AdSense pour afficher des publicités qui aident à couvrir ses frais. Google et ses partenaires peuvent utiliser des cookies pour afficher des annonces personnalisées en fonction de vos visites passées sur ce site ou sur d'autres.`,
        s5_li1: `Vous pouvez régler la personnalisation des annonces dans les <a href="https://myaccount.google.com/data-and-privacy" target="_blank" rel="noopener noreferrer">paramètres de votre compte Google</a>.`,
        s5_li2: `Pour savoir comment Google utilise les données, consultez <a href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer">l'utilisation des cookies publicitaires par Google</a>.`,
        s6_h: `6. Vos choix`,
        s6_p: `Vous pouvez à tout moment effacer les données localStorage du Site depuis les paramètres de votre navigateur. Si vous ne voulez pas qu'un message soit visible publiquement, n'utilisez simplement pas le livre d'or. Si vous ne voulez pas que le widget météo estime votre ville, laissez-le désactivé : les autres fonctions fonctionnent sans lui.`,
        s7_h: `7. Modifications de la politique`,
        s7_p: `Cette politique peut être mise à jour au fil de l'évolution du Site. Les modifications sont faites directement sur cette page, sans avis séparé ; pensez à revenir la consulter de temps en temps.`,
        s8_h: `8. Contact`,
        s8_p: `Pour toute question sur cette politique, écrivez-moi : <a href="mailto:azusawakohane12@gmail.com">azusawakohane12@gmail.com</a>`,
    },
    es: {
        doc_title: `Política de privacidad | Hanabiの小天地`,
        doc_desc: `Hanabiの小天地 – Política de privacidad`,
        back: `← Volver al inicio`,
        title: `Política de privacidad`,
        updated: `Última actualización: septiembre de 2026`,
        intro: `«Hanabiの小天地» (en adelante, «el Sitio») es un sitio web estático gestionado por una persona particular, con pruebas de vocabulario, reproductor de música, libro de visitas y otras funciones. Esta página explica qué datos usa el Sitio, de qué servicios de terceros depende y cómo puedes gestionar tus propios datos.`,
        s1_h: `1. Almacenamiento local del navegador (localStorage)`,
        s1_p1: `Los siguientes datos se guardan solo en el navegador de tu dispositivo y nunca se envían a los servidores del Sitio:`,
        s1_li1: `El tema (oscuro / claro) y el idioma elegido`,
        s1_li2: `El historial de pruebas, el cuaderno de errores y las tarjetas que ya has aprendido`,
        s1_li3: `El contenido del bloc de notas (si usas esa función)`,
        s1_p2: `Si borras los datos del navegador, cambias de dispositivo o usas el modo incógnito, todo lo anterior desaparecerá. Estos datos permanecen por completo en tu dispositivo; el Sitio no puede leerlos ni acceder a ellos.`,
        s2_h: `2. Libro de visitas`,
        s2_p: `Cuando usas el libro de visitas, el apodo y el mensaje que escribes se envían mediante Google Apps Script y se guardan en una hoja de Google Sheets del administrador del Sitio, y se muestran públicamente a todos los visitantes. Por favor, no incluyas tu nombre real, datos de contacto ni otra información personal sensible.`,
        s3_h: `3. Sugerencias`,
        s3_p: `Lo que envíes desde la página «Sugerencias» se transmite mediante Google Apps Script y se guarda en una hoja de Google Sheets que solo puede ver el administrador del Sitio; nunca se muestra públicamente. Junto con el mensaje se registran el idioma del Sitio y la ruta de la página en el momento del envío, para entender el contexto. No se registra nada más, salvo lo que tú mismo escribas en el mensaje.`,
        s4_h: `4. Servicios de terceros`,
        th_service: `Servicio`, th_purpose: `Uso`, th_data: `Datos que pueden verse implicados`,
        r1_purpose: `Guardar y leer el libro de visitas y las sugerencias`,
        r1_data: `El apodo, los mensajes y las sugerencias que escribes tú`,
        r2_purpose: `Contar las visitas al sitio`,
        r2_data: `Número de visitas anónimo`,
        r3_purpose: `Estimar tu ciudad a partir de la dirección IP para el widget del clima (solo después de pulsar «Mostrar el clima»; nunca se ejecuta solo)`,
        r3_data: `Dirección IP (solo para estimar la ubicación; no se guarda)`,
        r4_purpose: `Proporcionar información del clima`,
        r4_data: `Latitud y longitud (obtenidas de la localización por IP anterior)`,
        r5_service: `Google AdSense (previsto)`,
        r5_purpose: `Mostrar anuncios para mantener el Sitio`,
        r5_data: `Puede usar cookies para personalizar anuncios; ver más abajo`,
        r6_purpose: `Enlace de apoyo / donaciones`,
        r6_data: `Solo se aplica después de pulsar el botón de apoyo y salir hacia ko-fi.com; lo gestiona Ko-fi`,
        s5_h: `5. Publicidad y cookies`,
        s5_p: `El Sitio puede usar Google AdSense para mostrar anuncios que ayuden a cubrir sus costes. Google y sus socios pueden usar cookies para mostrar anuncios personalizados según tus visitas anteriores a este y a otros sitios web.`,
        s5_li1: `Puedes ajustar la personalización de anuncios en la <a href="https://myaccount.google.com/data-and-privacy" target="_blank" rel="noopener noreferrer">configuración de tu cuenta de Google</a>.`,
        s5_li2: `Para saber cómo usa Google los datos, consulta <a href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer">cómo utiliza Google las cookies en publicidad</a>.`,
        s6_h: `6. Tus opciones`,
        s6_p: `Puedes borrar en cualquier momento los datos de localStorage del Sitio desde la configuración del navegador. Si no quieres que un mensaje sea público, simplemente no uses el libro de visitas. Si no quieres que el widget del clima estime tu ciudad, no lo actives; las demás funciones siguen funcionando sin él.`,
        s7_h: `7. Cambios en esta política`,
        s7_p: `Esta política puede actualizarse a medida que cambien las funciones del Sitio. Los cambios se publican directamente en esta página, sin aviso aparte, así que conviene revisarla de vez en cuando.`,
        s8_h: `8. Contacto`,
        s8_p: `Si tienes alguna pregunta sobre esta política, escríbeme: <a href="mailto:azusawakohane12@gmail.com">azusawakohane12@gmail.com</a>`,
    },
    de: {
        doc_title: `Datenschutzerklärung | Hanabiの小天地`,
        doc_desc: `Hanabiの小天地 – Datenschutzerklärung`,
        back: `← Zurück zur Startseite`,
        title: `Datenschutzerklärung`,
        updated: `Zuletzt aktualisiert: September 2026`,
        intro: `„Hanabiの小天地“ (im Folgenden „die Website“) ist eine privat betriebene statische Website mit Vokabeltests, Musikwiedergabe, einem Gästebuch und weiteren Funktionen. Diese Seite erklärt, welche Daten die Website verwendet, welche Drittanbieterdienste sie nutzt und wie du deine eigenen Daten verwalten kannst.`,
        s1_h: `1. Lokaler Browserspeicher (localStorage)`,
        s1_p1: `Die folgenden Daten werden nur im Browser auf deinem eigenen Gerät gespeichert und nie an die Server der Website gesendet:`,
        s1_li1: `Design (dunkel / hell) und gewählte Sprache`,
        s1_li2: `Testverlauf, Fehlerheft und bereits gelernte Karteikarten`,
        s1_li3: `Inhalte der Notizen (wenn du die Notizfunktion nutzt)`,
        s1_p2: `Wenn du deine Browserdaten löschst, das Gerät wechselst oder den privaten Modus nutzt, geht all das verloren. Diese Daten bleiben vollständig auf deinem Gerät; die Website kann sie weder lesen noch darauf zugreifen.`,
        s2_h: `2. Gästebuch`,
        s2_p: `Wenn du das Gästebuch nutzt, werden der eingegebene Spitzname und die Nachricht über Google Apps Script an eine Google-Tabelle des Website-Betreibers gesendet, dort gespeichert und für alle Besucher öffentlich angezeigt. Bitte gib in Nachrichten keinen echten Namen, keine Kontaktdaten und keine anderen sensiblen persönlichen Informationen an.`,
        s3_h: `3. Vorschläge`,
        s3_p: `Was du auf der Seite „Vorschläge“ absendest, wird über Google Apps Script an eine Google-Tabelle gesendet und dort gespeichert, die nur der Website-Betreiber sehen kann; es wird nie öffentlich angezeigt. Zusammen mit der Nachricht werden die Sprache der Website und der Seitenpfad zum Zeitpunkt des Absendens gespeichert, um den Zusammenhang zu verstehen. Darüber hinaus wird nichts gespeichert, außer du schreibst es selbst in die Nachricht.`,
        s4_h: `4. Genutzte Drittanbieterdienste`,
        th_service: `Dienst`, th_purpose: `Zweck`, th_data: `Möglicherweise betroffene Daten`,
        r1_purpose: `Speichern und Laden von Gästebucheinträgen und Vorschlägen`,
        r1_data: `Spitzname, Nachrichten und Vorschläge, die du selbst eingibst`,
        r2_purpose: `Zählen der Seitenbesuche`,
        r2_data: `Anonyme Besuchszahl`,
        r3_purpose: `Schätzen deiner Stadt anhand der IP-Adresse für das Wetter-Widget (nur nach einem Klick auf „Wetter anzeigen“; läuft nie von selbst)`,
        r3_data: `IP-Adresse (nur zur Standortschätzung, wird nicht gespeichert)`,
        r4_purpose: `Bereitstellung von Wetterdaten`,
        r4_data: `Breiten- und Längengrad (aus der IP-Ortung oben)`,
        r5_service: `Google AdSense (geplant)`,
        r5_purpose: `Anzeigen zur Unterstützung der Website`,
        r5_data: `Kann Cookies zur Personalisierung von Anzeigen verwenden; siehe unten`,
        r6_purpose: `Unterstützungs- / Spendenlink`,
        r6_data: `Gilt erst, nachdem du auf den Unterstützen-Button klickst und zu ko-fi.com wechselst; wird von Ko-fi selbst verarbeitet`,
        s5_h: `5. Werbung und Cookies`,
        s5_p: `Die Website kann Google AdSense nutzen, um Anzeigen einzublenden, die die Betriebskosten decken. Google und seine Partner können Cookies verwenden, um personalisierte Anzeigen auf Grundlage deiner früheren Besuche auf dieser und anderen Websites zu zeigen.`,
        s5_li1: `Die Personalisierung von Anzeigen kannst du in deinen <a href="https://myaccount.google.com/data-and-privacy" target="_blank" rel="noopener noreferrer">Google-Kontoeinstellungen</a> anpassen.`,
        s5_li2: `Wie Google Daten verwendet, erfährst du unter <a href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer">So verwendet Google Cookies in der Werbung</a>.`,
        s6_h: `6. Deine Wahlmöglichkeiten`,
        s6_p: `Du kannst die localStorage-Daten der Website jederzeit über die Browsereinstellungen löschen. Wenn du nicht möchtest, dass eine Nachricht öffentlich sichtbar ist, nutze das Gästebuch einfach nicht. Wenn das Wetter-Widget deine Stadt nicht schätzen soll, lass es ausgeschaltet – alle anderen Funktionen funktionieren auch ohne.`,
        s7_h: `7. Änderungen dieser Erklärung`,
        s7_p: `Diese Erklärung kann aktualisiert werden, wenn sich die Funktionen der Website ändern. Änderungen erfolgen direkt auf dieser Seite ohne gesonderte Benachrichtigung – schau also ab und zu vorbei.`,
        s8_h: `8. Kontakt`,
        s8_p: `Bei Fragen zu dieser Erklärung schreib mir gern eine E-Mail: <a href="mailto:azusawakohane12@gmail.com">azusawakohane12@gmail.com</a>`,
    },
};

const PRIVACY_HTML_LANG = { zh: 'zh-TW', 'zh-Hans': 'zh-CN' };

(function applyPrivacyLang() {
    let lang = 'zh';
    try { lang = localStorage.getItem('site_lang') || 'zh'; } catch (e) {}
    const dict = PRIVACY[lang];
    if (!dict) return; // zh (or unknown): the markup already is the zh text
    document.documentElement.lang = PRIVACY_HTML_LANG[lang] || lang;
    document.querySelectorAll('[data-p]').forEach(el => {
        const key = el.getAttribute('data-p');
        if (dict[key]) el.innerHTML = dict[key];
    });
    document.title = dict.doc_title;
    const desc = document.querySelector('meta[name="description"]');
    if (desc) desc.setAttribute('content', dict.doc_desc);
})();
