"""Writes two generated files for the bot (re-run after the site's set or topic names change):

- src/site-strings.js: the word-set, topic and language names in the 9 site languages,
  read from the site's own i18n/<lang>.js, so the bot names things as the site does;
- src/zhconv.js: character tables Traditional <-> Simplified (OpenCC's STCharacters /
  TSCharacters, first choice, plus TWVariants), for the vocab meanings (written in
  Traditional) and Tatoeba's mixed-script Chinese. Character by character, like OpenCC tw2s.

    pip install opencc-python-reimplemented
    python worker/discord/build_strings.py
"""
import json, os, re

import opencc

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
# bot language code -> site i18n file
FILES = {"zh": "zh", "zhs": "zh-Hans", "en": "en", "ja": "ja", "ko": "ko", "ru": "ru", "fr": "fr", "es": "es", "de": "de"}
KEYS = ([f"dict_lang_{l}" for l in ("ja", "ko", "en", "zh", "fr", "ru", "es", "de")]
        + [f"topic_{t}" for t in ("greetings", "food", "home", "shopping", "transport", "travel", "weather", "school", "work", "health")]
        + [f"quiz_en_{s}" for s in ("jh", "sh", "toeic", "toefl")]
        + [f"quiz_jlpt_n{n}" for n in range(1, 6)] + [f"quiz_topik_{n}" for n in range(1, 5)] + [f"quiz_hsk_{n}" for n in range(1, 8)])


def site_strings():
    out = {}
    for code, name in FILES.items():
        src = open(os.path.join(ROOT, "i18n", name + ".js"), encoding="utf-8").read()
        d = {}
        for k in KEYS:
            m = re.search(r"\b" + k + r"""\s*:\s*(['"])((?:\\.|(?!\1).)*)\1""", src)
            if not m:
                raise SystemExit(f"{name}.js has no {k}")
            d[k] = m.group(2).replace("\\'", "'").replace('\\"', '"')
        out[code] = d
    return out


def char_table(fname):
    path = os.path.join(os.path.dirname(opencc.__file__), "dictionary", fname)
    table = {}
    for line in open(path, encoding="utf-8"):
        parts = line.rstrip("\n").split("\t")
        if len(parts) == 2 and len(parts[0]) == 1:
            first = parts[1].split(" ")[0]
            if len(first) == 1 and first != parts[0]:
                table[parts[0]] = first
    return table


def main():
    strings = site_strings()
    with open(os.path.join(HERE, "src", "site-strings.js"), "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by build_strings.py from the site's i18n/<lang>.js — don't edit by hand. */\n")
        f.write("export const SITE_STRINGS = " + json.dumps(strings, ensure_ascii=False, indent=1) + ";\n")

    t2s = char_table("TSCharacters.txt")
    s2t = char_table("STCharacters.txt")
    tw = char_table("TWVariants.txt")                     # 着 -> 著 etc. (Taiwan forms)
    s2t = {s: tw.get(t, t) for s, t in s2t.items()}
    for s, t in tw.items():
        s2t.setdefault(s, t)
    pairs = lambda d: ("".join(d.keys()), "".join(d.values()))
    (ta, sa), (sb, tb) = pairs(t2s), pairs(s2t)
    with open(os.path.join(HERE, "src", "zhconv.js"), "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by build_strings.py from OpenCC's character tables — don't edit by hand.\n"
                "   Character by character (like OpenCC tw2s): good enough for short meanings and examples. */\n")
        f.write(f"const T2S_FROM = {json.dumps(ta, ensure_ascii=False)};\nconst T2S_TO = {json.dumps(sa, ensure_ascii=False)};\n")
        f.write(f"const S2T_FROM = {json.dumps(sb, ensure_ascii=False)};\nconst S2T_TO = {json.dumps(tb, ensure_ascii=False)};\n")
        f.write("""
function table(from, to) {
    const m = new Map();
    const a = [...from], b = [...to];
    a.forEach((c, i) => m.set(c, b[i]));
    return m;
}
let t2s = null, s2t = null;

export function toSimplified(text) {
    t2s = t2s || table(T2S_FROM, T2S_TO);
    return [...String(text || '')].map(c => t2s.get(c) || c).join('');
}

export function toTraditional(text) {
    s2t = s2t || table(S2T_FROM, S2T_TO);
    return [...String(text || '')].map(c => s2t.get(c) || c).join('');
}
""")
    print("site strings:", {k: len(v) for k, v in strings.items()}, "| t2s", len(t2s), "s2t", len(s2t))


if __name__ == "__main__":
    main()
